import type { Language } from './dict';
// Fixed keys, complete coverage of all game languages (including errors and help).
const keys = ['reset','enroll','enrollHelp','resetHelp','email','code','send','verify','password','repeat','saved','sent','unavailable','failed','passwordRule','mismatch'] as const;
const copy: Record<Language, readonly string[]> = {
    ja:['パスワードを忘れた場合','復旧用メールを確認','現在のパスワードとメールの確認コードで本人確認します。メールは初回登録後、この画面では変更できません。','IDと、事前に確認済みの復旧用メールを入力してください。Google・Discordでログインする場合は、各サービス側で復旧してください。','メールアドレス','確認コード','コードを送信','確認して保存','新しいパスワード','新しいパスワード（確認）','保存しました。パスワードを再設定した場合は、新しいパスワードでログインしてください。','対象の確認済みメールが登録されていればコードを送ります。メールを確認してください。コードは10分以内に入力してください。','現在この機能は利用できません。準備完了後にもう一度お試しください。','確認できませんでした。入力・接続を確認し、対局中の場合は終了後、少し待って再試行してください。','パスワードは12文字以上・UTF-8で72バイト以内にしてください。','パスワードが一致しません。'],
    en:['Forgot password?','Verify recovery email','Verify using your current password and an email code. Once linked, the email cannot be changed on this screen.','Enter your ID and previously verified recovery email. For Google or Discord sign-in, recover your account through that provider.','Email address','Verification code','Send code','Verify and save','New password','Repeat new password','Saved. If you reset your password, sign in with the new password.','If a matching verified email is registered, a code will be sent. Check your email and enter the code within 10 minutes.','This feature is currently unavailable. Please try again when it is ready.','Could not verify. Check your input and connection, finish any active match, wait a moment and try again.','Use at least 12 characters and no more than 72 UTF-8 bytes.','Passwords do not match.'],
    zh:['忘记密码？','验证恢复邮箱','使用当前密码和邮件验证码验证身份。绑定后无法在此页面更改邮箱。','输入ID和预先验证的恢复邮箱。Google或Discord账户请通过对应服务恢复。','邮箱地址','验证码','发送验证码','验证并保存','新密码','再次输入新密码','已保存。如已重置密码，请用新密码登录。','若已登记匹配的验证邮箱，将发送验证码。请查收并在10分钟内输入。','此功能暂不可用，请在准备完成后重试。','无法验证。请检查输入和连接，结束当前对局，稍后重试。','至少12个字符，UTF-8编码不超过72字节。','两次密码不一致。'],
    ru:['Забыли пароль?','Подтвердить почту восстановления','Подтвердите текущий пароль и код из письма. После привязки адрес нельзя изменить на этом экране.','Введите ID и ранее подтверждённую почту. Для Google или Discord используйте восстановление соответствующего сервиса.','Электронная почта','Код подтверждения','Отправить код','Подтвердить и сохранить','Новый пароль','Повторите новый пароль','Сохранено. После сброса войдите с новым паролем.','Если подходящий подтверждённый адрес зарегистрирован, на него придёт код. Введите его в течение 10 минут.','Функция пока недоступна. Повторите после её подключения.','Проверка не удалась. Проверьте данные и соединение, завершите партию и повторите чуть позже.','Не менее 12 символов и не более 72 байт UTF-8.','Пароли не совпадают.'],
    fr:['Mot de passe oublié ?','Vérifier l’adresse de récupération','Vérifiez votre mot de passe actuel et le code reçu. Une fois liée, l’adresse ne peut pas être modifiée ici.','Saisissez votre ID et l’adresse déjà vérifiée. Pour Google ou Discord, utilisez la récupération du service concerné.','Adresse e-mail','Code de vérification','Envoyer le code','Vérifier et enregistrer','Nouveau mot de passe','Confirmer le nouveau mot de passe','Enregistré. Après réinitialisation, connectez-vous avec le nouveau mot de passe.','Si une adresse vérifiée correspond, un code sera envoyé. Consultez votre messagerie et saisissez-le sous 10 minutes.','Cette fonction est indisponible pour le moment. Réessayez une fois disponible.','Vérification impossible. Contrôlez les données et la connexion, terminez la partie et réessayez un peu plus tard.','Au moins 12 caractères, au maximum 72 octets UTF-8.','Les mots de passe ne correspondent pas.'],
    de:['Passwort vergessen?','Wiederherstellungs-E-Mail bestätigen','Bestätige dein aktuelles Passwort und den E-Mail-Code. Die verknüpfte Adresse kann hier nicht geändert werden.','Gib deine ID und die bereits bestätigte E-Mail ein. Bei Google oder Discord nutze die Wiederherstellung des jeweiligen Anbieters.','E-Mail-Adresse','Bestätigungscode','Code senden','Bestätigen und speichern','Neues Passwort','Neues Passwort wiederholen','Gespeichert. Melde dich nach dem Zurücksetzen mit dem neuen Passwort an.','Ist eine passende bestätigte Adresse registriert, wird ein Code gesendet. Gib ihn innerhalb von 10 Minuten ein.','Diese Funktion ist noch nicht verfügbar. Versuche es später erneut.','Bestätigung fehlgeschlagen. Prüfe Eingaben und Verbindung, beende die Partie und versuche es etwas später erneut.','Mindestens 12 Zeichen, höchstens 72 UTF-8-Bytes.','Die Passwörter stimmen nicht überein.'],
    es:['¿Olvidaste tu contraseña?','Verificar correo de recuperación','Verifica tu contraseña actual y el código del correo. Una vez vinculado, el correo no se puede cambiar aquí.','Introduce tu ID y el correo verificado previamente. Para Google o Discord, usa la recuperación de ese servicio.','Correo electrónico','Código de verificación','Enviar código','Verificar y guardar','Nueva contraseña','Repetir nueva contraseña','Guardado. Tras restablecerla, inicia sesión con la nueva contraseña.','Si hay un correo verificado coincidente, se enviará un código. Revísalo e introdúcelo en 10 minutos.','Esta función aún no está disponible. Inténtalo cuando esté lista.','No se pudo verificar. Revisa los datos y la conexión, termina la partida y vuelve a intentarlo en un momento.','Al menos 12 caracteres y como máximo 72 bytes UTF-8.','Las contraseñas no coinciden.'],
    tr:['Şifrenizi mi unuttunuz?','Kurtarma e-postasını doğrula','Mevcut şifrenizi ve e-posta kodunu doğrulayın. Bağlanan adres bu ekranda değiştirilemez.','Kimliğinizi ve önceden doğrulanmış e-postanızı girin. Google veya Discord için ilgili hizmetin kurtarma seçeneğini kullanın.','E-posta adresi','Doğrulama kodu','Kod gönder','Doğrula ve kaydet','Yeni şifre','Yeni şifreyi tekrarla','Kaydedildi. Şifrenizi sıfırladıysanız yeni şifreyle giriş yapın.','Eşleşen doğrulanmış adres kayıtlıysa kod gönderilir. E-postanızı kontrol edip 10 dakika içinde girin.','Bu özellik şu anda kullanılamıyor. Hazır olduğunda tekrar deneyin.','Doğrulanamadı. Bilgileri ve bağlantıyı kontrol edin, maçı bitirin ve biraz sonra tekrar deneyin.','En az 12 karakter ve en fazla 72 UTF-8 bayt kullanın.','Şifreler eşleşmiyor.'],
    pl:['Nie pamiętasz hasła?','Potwierdź e-mail odzyskiwania','Potwierdź obecne hasło i kod z e-maila. Po powiązaniu adresu nie można zmienić na tym ekranie.','Podaj ID i wcześniej potwierdzony adres. W przypadku Google lub Discord użyj odzyskiwania konta danej usługi.','Adres e-mail','Kod weryfikacyjny','Wyślij kod','Potwierdź i zapisz','Nowe hasło','Powtórz nowe hasło','Zapisano. Po zresetowaniu zaloguj się nowym hasłem.','Jeśli pasujący potwierdzony adres jest zapisany, wyślemy kod. Sprawdź pocztę i wpisz go w ciągu 10 minut.','Ta funkcja jest obecnie niedostępna. Spróbuj po jej uruchomieniu.','Weryfikacja nie powiodła się. Sprawdź dane i połączenie, zakończ partię i spróbuj za chwilę.','Co najmniej 12 znaków i najwyżej 72 bajty UTF-8.','Hasła są różne.'],
    hi:['पासवर्ड भूल गए?','रिकवरी ईमेल सत्यापित करें','वर्तमान पासवर्ड और ईमेल कोड से पुष्टि करें। जोड़ने के बाद ईमेल इस स्क्रीन पर नहीं बदला जा सकता।','अपना ID और पहले सत्यापित रिकवरी ईमेल डालें। Google या Discord के लिए उसी सेवा की रिकवरी सुविधा इस्तेमाल करें।','ईमेल पता','सत्यापन कोड','कोड भेजें','सत्यापित करके सहेजें','नया पासवर्ड','नया पासवर्ड दोहराएँ','सहेजा गया। पासवर्ड बदला है तो नए पासवर्ड से लॉग इन करें।','मेल खाता सत्यापित और पंजीकृत होने पर कोड भेजा जाएगा। ईमेल देखें और 10 मिनट में कोड डालें।','यह सुविधा अभी उपलब्ध नहीं है। तैयार होने पर फिर कोशिश करें।','सत्यापन नहीं हुआ। जानकारी और कनेक्शन जाँचें, चालू खेल पूरा करें और थोड़ी देर बाद कोशिश करें।','कम से कम 12 अक्षर और अधिकतम 72 UTF-8 बाइट रखें।','पासवर्ड मेल नहीं खाते।'],
    pt:['Esqueceu a senha?','Verificar e-mail de recuperação','Confirme sua senha atual e o código por e-mail. Após vincular, o endereço não pode ser alterado nesta tela.','Informe seu ID e o e-mail já verificado. Para Google ou Discord, use a recuperação do respectivo serviço.','Endereço de e-mail','Código de verificação','Enviar código','Verificar e salvar','Nova senha','Repetir nova senha','Salvo. Após redefinir, entre com a nova senha.','Se houver um e-mail verificado correspondente, enviaremos um código. Confira a caixa de entrada e digite em até 10 minutos.','Esta função ainda não está disponível. Tente quando estiver pronta.','Não foi possível verificar. Confira os dados e a conexão, termine a partida e tente novamente em instantes.','Use pelo menos 12 caracteres e no máximo 72 bytes UTF-8.','As senhas não coincidem.'],
    ta:['கடவுச்சொல் மறந்துவிட்டதா?','மீட்பு மின்னஞ்சலைச் சரிபார்க்கவும்','தற்போதைய கடவுச்சொல் மற்றும் மின்னஞ்சல் குறியீட்டால் உறுதிசெய்யவும். இணைத்த பிறகு இந்தத் திரையில் முகவரியை மாற்ற முடியாது.','உங்கள் ID மற்றும் முன்பே சரிபார்க்கப்பட்ட மீட்பு மின்னஞ்சலை உள்ளிடவும். Google அல்லது Discord உள்நுழைவிற்கு அந்தச் சேவையின் மீட்பைப் பயன்படுத்தவும்.','மின்னஞ்சல் முகவரி','சரிபார்ப்புக் குறியீடு','குறியீட்டை அனுப்பு','சரிபார்த்துச் சேமி','புதிய கடவுச்சொல்','புதிய கடவுச்சொல்லை மீண்டும் உள்ளிடு','சேமிக்கப்பட்டது. கடவுச்சொல்லை மாற்றியிருந்தால் புதிய கடவுச்சொல்லுடன் உள்நுழையவும்.','பொருந்தும் சரிபார்க்கப்பட்ட மின்னஞ்சல் பதிவாகியிருந்தால் குறியீடு அனுப்பப்படும். மின்னஞ்சலைப் பார்த்து 10 நிமிடங்களுக்குள் உள்ளிடவும்.','இந்த வசதி தற்போது கிடைக்கவில்லை. தயாரான பிறகு மீண்டும் முயலவும்.','சரிபார்க்க முடியவில்லை. உள்ளீடு மற்றும் இணைப்பைச் சரிபார்த்து, ஆட்டத்தை முடித்து, சிறிது நேரம் கழித்து முயலவும்.','குறைந்தது 12 எழுத்துகள்; UTF-8 அளவு அதிகபட்சம் 72 பைட்டுகள்.','கடவுச்சொற்கள் பொருந்தவில்லை.'],
};
export function accountRecoveryText(lang:Language) {
    return Object.fromEntries(keys.map((key,index)=>[key,copy[lang][index]])) as Record<typeof keys[number],string>;
}
