import type {Language} from './dict';
type Key='logoutAll'|'confirm'|'explain'|'failed'|'registered'|'rules'|'copy'|'copied';
const keys:Key[]=['logoutAll','confirm','explain','failed','registered','rules','copy','copied'];
const messages:Record<Language,readonly string[]>={
    ja:['全端末からログアウト','ログアウトする','この端末を含む全端末で、再ログインが必要になります。','処理できませんでした。時間をおいて再度お試しください。','登録できました。ログインをお試しください。','IDは半角英数字3〜15文字。パスワードは12文字以上・72バイト以内で、推測されにくいものを使ってください。','問い合わせIDをコピー','コピーしました'],
    en:['Sign out everywhere','Sign out','You will need to sign in again on every device, including this one.','Could not complete the request. Try again shortly.','Account created. Please sign in.','ID: 3–15 letters/numbers. Use a hard-to-guess password of at least 12 characters, up to 72 UTF-8 bytes.','Copy support ID','Copied'],
    zh:['退出所有设备','退出','包括当前设备在内，所有设备都需要重新登录。','无法完成，请稍后重试。','账号已创建，请登录。','ID为3至15位英文字母或数字。密码至少12个字符，最多72字节，请使用难以猜测的密码。','复制支持ID','已复制'],
    ru:['Выйти на всех устройствах','Выйти','На всех устройствах, включая это, потребуется повторный вход.','Не удалось выполнить запрос. Повторите позже.','Аккаунт создан. Войдите.','ID: 3–15 латинских букв/цифр. Сложный пароль: от 12 символов до 72 байт UTF-8.','Копировать ID поддержки','Скопировано'],
    fr:['Déconnexion partout','Se déconnecter','Reconnectez-vous sur tous les appareils, y compris celui-ci.','Échec de la demande. Réessayez plus tard.','Compte créé. Connectez-vous.','ID : 3–15 lettres/chiffres ASCII. Mot de passe difficile à deviner : 12 caractères minimum, 72 octets UTF-8 maximum.','Copier l’ID de support','Copié'],
    de:['Überall abmelden','Abmelden','Auf allen Geräten einschließlich diesem ist eine neue Anmeldung nötig.','Anfrage fehlgeschlagen. Bitte später erneut versuchen.','Konto erstellt. Bitte anmelden.','ID: 3–15 ASCII-Buchstaben/Ziffern. Schwer erratbares Passwort: mindestens 12 Zeichen, maximal 72 UTF-8-Bytes.','Support-ID kopieren','Kopiert'],
    es:['Cerrar sesión en todos los dispositivos','Cerrar sesión','Tendrás que iniciar sesión de nuevo en todos los dispositivos, incluido este.','No se pudo completar. Inténtalo más tarde.','Cuenta creada. Inicia sesión.','ID: 3–15 letras/números ASCII. Contraseña difícil de adivinar: mínimo 12 caracteres y máximo 72 bytes UTF-8.','Copiar ID de soporte','Copiado'],
    tr:['Tüm cihazlardan çıkış yap','Çıkış yap','Bu cihaz dahil tüm cihazlarda yeniden giriş yapmanız gerekir.','İşlem tamamlanamadı. Biraz sonra deneyin.','Hesap oluşturuldu. Giriş yapın.','Kimlik: 3–15 ASCII harfi/rakamı. Tahmini zor parola: en az 12 karakter, en fazla 72 UTF-8 bayt.','Destek kimliğini kopyala','Kopyalandı'],
    pl:['Wyloguj ze wszystkich urządzeń','Wyloguj','Na wszystkich urządzeniach, także tym, konieczne będzie ponowne logowanie.','Nie udało się wykonać operacji. Spróbuj później.','Konto utworzone. Zaloguj się.','ID: 3–15 liter/cyfr ASCII. Trudne do odgadnięcia hasło: co najmniej 12 znaków, do 72 bajtów UTF-8.','Kopiuj ID pomocy','Skopiowano'],
    hi:['सभी उपकरणों से लॉग आउट करें','लॉग आउट करें','इस उपकरण सहित सभी उपकरणों पर फिर से लॉग इन करना होगा।','अनुरोध पूरा नहीं हुआ। थोड़ी देर बाद कोशिश करें।','खाता बन गया। लॉग इन करें।','ID: 3–15 अंग्रेज़ी अक्षर/अंक। कठिन पासवर्ड: कम से कम 12 अक्षर, अधिकतम 72 UTF-8 बाइट।','सहायता ID कॉपी करें','कॉपी हो गया'],
    pt:['Sair de todos os dispositivos','Sair','Será necessário entrar novamente em todos os dispositivos, incluindo este.','Não foi possível concluir. Tente mais tarde.','Conta criada. Entre na conta.','ID: 3–15 letras/números ASCII. Senha difícil de adivinhar: mínimo de 12 caracteres e máximo de 72 bytes UTF-8.','Copiar ID de suporte','Copiado'],
    ta:['அனைத்து சாதனங்களிலிருந்தும் வெளியேறு','வெளியேறு','இந்தச் சாதனம் உட்பட அனைத்திலும் மீண்டும் உள்நுழைய வேண்டும்.','கோரிக்கையை முடிக்க முடியவில்லை. பிறகு முயலவும்.','கணக்கு உருவாக்கப்பட்டது. உள்நுழையவும்.','ID: 3–15 ஆங்கில எழுத்துகள்/எண்கள். கணிக்க முடியாத கடவுச்சொல்: குறைந்தது 12 எழுத்துகள், அதிகபட்சம் 72 UTF-8 பைட்டுகள்.','உதவி IDஐ நகலெடு','நகலெடுக்கப்பட்டது'],
};
export const accountSecurityText=(lang:Language,key:Key)=>messages[lang][keys.indexOf(key)];
