import type { Language } from './dict';

// How to request erasure; what remains; verified email recovery.
const copy: Record<Language, readonly [string, string, string]> = {
  ja: ['Q-Gambitにログインし、設定 → アカウント管理 → アカウントを削除を開きます。対局・保存を終了し、内容を確認して DELETE と入力すると確定できます。ログインできない場合は下記へ削除を依頼してください。パスワードや確認コードは送らないでください。', '削除完了後は元に戻せません。相手のレートは変わりません。バックアップは通常の保管期間後に消去され、他端末の保存データやダウンロード済みコピーを遠隔で消すことはできません。', 'ID・パスワードのアカウントは、ログイン後のアカウント管理でメールを認証してから再設定を利用できます。未認証のメールは再設定に使えません。Google・Discordの復旧は各サービスで行ってください。'],
  en: ['Sign in to Q-Gambit, then open Settings → Account management → Delete account. Finish your match and pending saves, review the warning and type DELETE to confirm. If you cannot sign in, request deletion at the address below. Never send passwords or verification codes.', 'Completed deletion cannot be undone. Opponents keep their ratings. Backup copies expire under the hosting provider’s retention schedule; stored copies on other devices and downloads cannot be erased remotely.', 'For an ID/password account, verify a recovery email in account settings while signed in before using password recovery. Unverified addresses cannot reset passwords. Recover Google or Discord access through that provider.'],
  zh: ['登录Q-Gambit，打开设置 → 账户管理 → 删除账户。结束对局及保存后，阅读提示并输入 DELETE 确认。无法登录时请通过下方地址申请删除。切勿发送密码或验证码。', '删除完成后无法恢复，对手评分不变。备份按托管服务的保留期限到期清除，无法远程删除其他设备或下载的副本。', 'ID/密码账户须先在账户设置中验证恢复邮箱。未验证的邮箱不能重设密码。Google或Discord账户请通过对应服务恢复。'],
  ru: ['Войдите в Q-Gambit: Настройки → Управление аккаунтом → Удалить аккаунт. Завершите партию и сохранение, прочитайте предупреждение и введите DELETE. Если вход недоступен, напишите по адресу ниже. Не отправляйте пароли и коды.', 'Удаление необратимо. Рейтинг соперников не меняется. Резервные копии удаляются по срокам хранения хостинга; копии на других устройствах и загрузки нельзя стереть удалённо.', 'Для аккаунта с ID и паролем сначала подтвердите почту восстановления в настройках. Неподтверждённая почта не подходит. Доступ к Google и Discord восстанавливается у соответствующего провайдера.'],
  fr: ['Connectez-vous à Q-Gambit : Paramètres → Gestion du compte → Supprimer le compte. Terminez la partie et les sauvegardes, lisez l’avertissement puis saisissez DELETE. Si la connexion est impossible, contactez l’adresse ci-dessous. N’envoyez ni mot de passe ni code.', 'La suppression est irréversible. Le classement des adversaires reste inchangé. Les sauvegardes expirent selon la rétention de l’hébergeur ; les copies téléchargées ou sur d’autres appareils ne peuvent pas être effacées à distance.', 'Pour un compte avec identifiant et mot de passe, vérifiez d’abord une adresse de récupération dans les paramètres. Une adresse non vérifiée ne suffit pas. Récupérez Google ou Discord auprès du fournisseur.'],
  de: ['Melde dich bei Q-Gambit an: Einstellungen → Kontoverwaltung → Konto löschen. Beende Partie und Speichervorgänge, lies die Warnung und gib DELETE ein. Falls keine Anmeldung möglich ist, nutze die Adresse unten. Sende keine Passwörter oder Codes.', 'Die Löschung ist endgültig. Gegner behalten ihre Wertungen. Sicherungskopien verfallen nach den Aufbewahrungsfristen des Hosters; Downloads und Kopien auf anderen Geräten lassen sich nicht fernlöschen.', 'Bestätige für ein Konto mit ID und Passwort zuerst eine Wiederherstellungs-E-Mail in den Kontoeinstellungen. Unbestätigte Adressen reichen nicht aus. Google- und Discord-Zugänge werden beim jeweiligen Anbieter wiederhergestellt.'],
  es: ['Inicia sesión en Q-Gambit: Ajustes → Gestión de cuenta → Eliminar cuenta. Termina la partida y los guardados, lee el aviso y escribe DELETE. Si no puedes entrar, solicita la eliminación en la dirección inferior. No envíes contraseñas ni códigos.', 'La eliminación es irreversible. La puntuación de los rivales no cambia. Las copias de seguridad caducan según la retención del proveedor; no se pueden borrar remotamente las descargas o copias de otros dispositivos.', 'Para cuentas con ID y contraseña, verifica primero un correo de recuperación en los ajustes. Los correos sin verificar no permiten restablecer la contraseña. Recupera Google o Discord con su proveedor.'],
  tr: ['Q-Gambit’e giriş yapın: Ayarlar → Hesap yönetimi → Hesabı sil. Maçı ve kayıt işlemlerini bitirin, uyarıyı okuyup DELETE yazın. Giriş yapamıyorsanız aşağıdaki adresten silme isteyin. Parola veya doğrulama kodu göndermeyin.', 'Tamamlanan silme geri alınamaz. Rakiplerin puanı değişmez. Yedekler barındırma sağlayıcısının saklama süresine göre silinir; diğer cihazlardaki ve indirilen kopyalar uzaktan silinemez.', 'ID/parola hesabı için önce hesap ayarlarında kurtarma e-postasını doğrulayın. Doğrulanmamış adresler parola sıfırlayamaz. Google veya Discord erişimini kendi sağlayıcısından kurtarın.'],
  pl: ['Zaloguj się do Q-Gambit: Ustawienia → Zarządzanie kontem → Usuń konto. Zakończ partię i zapis, przeczytaj ostrzeżenie i wpisz DELETE. Jeśli nie możesz się zalogować, napisz na adres poniżej. Nie wysyłaj haseł ani kodów.', 'Usunięcie jest nieodwracalne. Ranking przeciwników nie zmienia się. Kopie zapasowe wygasają zgodnie z retencją hostingu; pobranych kopii i danych na innych urządzeniach nie można usunąć zdalnie.', 'Dla konta z ID i hasłem najpierw potwierdź e-mail odzyskiwania w ustawieniach. Niepotwierdzony adres nie pozwala zresetować hasła. Dostęp do Google lub Discord odzyskuj u dostawcy.'],
  hi: ['Q-Gambit में लॉग इन करें: सेटिंग → खाता प्रबंधन → खाता मिटाएँ। मैच और सेव पूरा करें, चेतावनी पढ़ें और पुष्टि के लिए DELETE लिखें। लॉग इन न हो पाए तो नीचे दिए पते पर मिटाने का अनुरोध करें। पासवर्ड या सत्यापन कोड न भेजें।', 'मिटाने के बाद वापस नहीं लाया जा सकता। विरोधियों की रेटिंग नहीं बदलती। बैकअप होस्टिंग प्रदाता की अवधि के अनुसार हटते हैं; दूसरे उपकरणों और डाउनलोड की प्रतियाँ दूर से नहीं मिटाई जा सकतीं।', 'ID/पासवर्ड खाते में पहले खाता सेटिंग में रिकवरी ईमेल सत्यापित करें। असत्यापित ईमेल से पासवर्ड नहीं बदल सकता। Google या Discord का खाता उसी सेवा से वापस पाएँ।'],
  pt: ['Entre no Q-Gambit: Configurações → Gestão da conta → Excluir conta. Termine a partida e os salvamentos, leia o aviso e digite DELETE. Se não conseguir entrar, solicite a exclusão pelo endereço abaixo. Não envie senhas nem códigos.', 'A exclusão é irreversível. A pontuação dos adversários não muda. Backups expiram conforme a retenção da hospedagem; downloads e cópias em outros dispositivos não podem ser apagados remotamente.', 'Para contas com ID e senha, verifique primeiro um e-mail de recuperação nas configurações. Endereços não verificados não permitem redefinir senhas. Recupere Google ou Discord no respectivo provedor.'],
  ta: ['Q-Gambit இல் உள்நுழைந்து அமைப்புகள் → கணக்கு மேலாண்மை → கணக்கை நீக்கு என்பதைத் திறக்கவும். ஆட்டத்தையும் சேமிப்பையும் முடித்து, எச்சரிக்கையைப் படித்து DELETE என உள்ளிடவும். உள்நுழைய முடியாவிட்டால் கீழுள்ள முகவரியில் நீக்கக் கோரவும். கடவுச்சொல் அல்லது சரிபார்ப்புக் குறியீட்டை அனுப்ப வேண்டாம்.', 'நீக்கிய பிறகு மீட்டெடுக்க முடியாது. எதிராளிகளின் மதிப்பீடு மாறாது. காப்புப்பிரதிகள் வழங்குநரின் சேமிப்புக் காலத்திற்குப் பிறகு நீங்கும்; மற்ற சாதனங்கள் மற்றும் பதிவிறக்க நகல்களைத் தொலைவிலிருந்து அழிக்க முடியாது.', 'ID/கடவுச்சொல் கணக்கிற்கு முதலில் கணக்கு அமைப்புகளில் மீட்பு மின்னஞ்சலைச் சரிபார்க்கவும். சரிபார்க்காத முகவரியால் கடவுச்சொல்லை மாற்ற முடியாது. Google அல்லது Discord கணக்கை அந்தச் சேவையிலேயே மீட்கவும்.'],
};
export const accountDataGuide = (lang: Language) => copy[lang];
