import type { Language } from './dict';
const cleanupWarning: Record<Language,string> = {
    ja:'サーバー上の削除は完了しましたが、この端末の保存領域の一部を消去できませんでした。ログアウト後、ブラウザのサイトデータ、またはAndroid設定のアプリデータを消去してください。',
    en:'Server deletion is complete, but some data on this device could not be cleared. After signing out, clear this site’s browser data or the app’s storage in Android settings.',
    zh:'服务器数据已删除，但未能清除本设备上的部分数据。退出后，请清除此网站的浏览器数据或Android设置中的应用数据。',
    ru:'Данные на сервере удалены, но часть данных на устройстве очистить не удалось. После выхода удалите данные сайта в браузере или данные приложения в настройках Android.',
    fr:'La suppression sur le serveur est terminée, mais certaines données locales restent présentes. Après déconnexion, effacez les données du site dans le navigateur ou de l’application dans les paramètres Android.',
    de:'Die Serverdaten wurden gelöscht, einige lokale Daten jedoch nicht. Lösche nach dem Abmelden die Websitedaten im Browser oder die App-Daten in den Android-Einstellungen.',
    es:'Los datos del servidor se han borrado, pero no algunos datos locales. Tras cerrar sesión, borra los datos del sitio en el navegador o los de la app en los ajustes de Android.',
    tr:'Sunucudaki silme tamamlandı, ancak bazı yerel veriler silinemedi. Çıkış yaptıktan sonra tarayıcıdaki site verilerini veya Android ayarlarındaki uygulama verilerini silin.',
    pl:'Dane na serwerze zostały usunięte, ale niektóre dane lokalne pozostały. Po wylogowaniu wyczyść dane witryny w przeglądarce lub aplikacji w ustawieniach Androida.',
    hi:'सर्वर से डेटा मिट गया है, लेकिन इस डिवाइस का कुछ डेटा नहीं मिट सका। लॉग आउट करने के बाद ब्राउज़र का साइट डेटा या Android सेटिंग में ऐप का डेटा मिटाएँ।',
    pt:'Os dados do servidor foram excluídos, mas alguns dados locais não puderam ser apagados. Após sair, limpe os dados do site no navegador ou do app nas configurações do Android.',
    ta:'சேவையகத் தரவு நீக்கப்பட்டது. ஆனால் சாதனத்தில் சில தரவுகளை நீக்க முடியவில்லை. வெளியேறிய பிறகு உலாவியின் தளத் தரவு அல்லது Android அமைப்புகளில் செயலியின் தரவை அழிக்கவும்.',
};
// title, scope, confirmation, action, cancel, busy, unavailable, reauthenticate, working, done
const copy: Record<Language, readonly string[]> = {
    ja: ['アカウントを削除','アカウント・レート・画像・フレンド情報と、この端末の進行データを削除します。共有棋譜は消去し、相手には匿名の勝敗記録だけが残ります。取り消せません。Googleアカウント自体や、他の端末に保存済みのコピーは削除されません。','確認のため DELETE と入力','完全に削除する','キャンセル','対局やデータ保存が終わってから再試行してください。','削除の完了を確認できません。接続を確認して再試行してください。未対応の旧サーバーの場合は準備完了まで利用できません。','本人確認のため、もう一度ログインしてください。','削除しています。完了するまでお待ちください。','アカウントを削除しました。'],
    en: ['Delete account','Delete your account, rating, photos, friends and progress on this device. Shared replays are erased; opponents keep anonymous win/loss records only. This cannot be undone. Your Google account and copies on other devices are not deleted.','Type DELETE to confirm','Delete permanently','Cancel','Finish your match or pending save, then try again.','Deletion is not confirmed. Check your connection and retry. Older servers may not support deletion yet.','Sign in again to verify your identity.','Deleting. Please wait for confirmation.','Your account has been deleted.'],
    zh: ['删除账户','删除账户、评分、照片、好友和此设备上的进度。共享棋谱将删除，对手仅保留匿名胜负记录。无法撤销。不会删除Google账户或其他设备上保存的副本。','输入 DELETE 确认','永久删除','取消','请先结束对局或等待保存完成，再重试。','尚未确认删除完成。请检查连接并重试。旧服务器可能尚不支持删除。','请重新登录以验证身份。','正在删除，请等待确认。','账户已删除。'],
    ru: ['Удалить аккаунт','Будут удалены аккаунт, рейтинг, фото, друзья и прогресс на этом устройстве. Повторы удаляются; соперникам остаются анонимные результаты. Отмена невозможна. Аккаунт Google и копии на других устройствах не удаляются.','Введите DELETE для подтверждения','Удалить навсегда','Отмена','Завершите партию или сохранение и повторите.','Удаление не подтверждено. Проверьте связь и повторите. Старый сервер может не поддерживать удаление.','Войдите снова для проверки личности.','Удаление. Дождитесь подтверждения.','Аккаунт удалён.'],
    fr: ['Supprimer le compte','Supprime le compte, le classement, les photos, les amis et la progression sur cet appareil. Les replays sont effacés ; les adversaires gardent uniquement des résultats anonymes. Action irréversible. Votre compte Google et les copies sur d’autres appareils restent intacts.','Saisissez DELETE pour confirmer','Supprimer définitivement','Annuler','Terminez la partie ou la sauvegarde, puis réessayez.','Suppression non confirmée. Vérifiez la connexion et réessayez. Un ancien serveur peut ne pas la prendre en charge.','Reconnectez-vous pour vérifier votre identité.','Suppression en cours. Veuillez patienter.','Votre compte a été supprimé.'],
    de: ['Konto löschen','Konto, Wertung, Fotos, Freunde und Fortschritt auf diesem Gerät werden gelöscht. Wiederholungen werden entfernt; Gegner behalten nur anonyme Ergebnisse. Nicht rückgängig zu machen. Google-Konto und Kopien auf anderen Geräten bleiben bestehen.','Zur Bestätigung DELETE eingeben','Endgültig löschen','Abbrechen','Beende die Partie oder den Speichervorgang und versuche es erneut.','Löschung nicht bestätigt. Prüfe die Verbindung und versuche es erneut. Ältere Server unterstützen dies eventuell noch nicht.','Melde dich zur Identitätsprüfung erneut an.','Wird gelöscht. Bitte warte auf die Bestätigung.','Dein Konto wurde gelöscht.'],
    es: ['Eliminar cuenta','Se borrarán la cuenta, puntuación, fotos, amigos y progreso de este dispositivo. Se eliminan las repeticiones; los rivales conservan solo resultados anónimos. Es irreversible. No se borra tu cuenta de Google ni las copias en otros dispositivos.','Escribe DELETE para confirmar','Eliminar definitivamente','Cancelar','Termina la partida o el guardado e inténtalo de nuevo.','El borrado no está confirmado. Revisa la conexión y reintenta. Los servidores antiguos pueden no admitirlo.','Inicia sesión de nuevo para verificar tu identidad.','Eliminando. Espera la confirmación.','Tu cuenta se ha eliminado.'],
    tr: ['Hesabı sil','Hesap, puan, fotoğraflar, arkadaşlar ve bu cihazdaki ilerleme silinir. Tekrarlar silinir; rakiplerde yalnızca anonim sonuçlar kalır. Geri alınamaz. Google hesabınız ve diğer cihazlardaki kopyalar silinmez.','Onaylamak için DELETE yazın','Kalıcı olarak sil','İptal','Maç veya kayıt işlemi bitince tekrar deneyin.','Silme onaylanmadı. Bağlantıyı kontrol edip tekrar deneyin. Eski sunucular silmeyi desteklemeyebilir.','Kimliğinizi doğrulamak için yeniden giriş yapın.','Siliniyor. Onayı bekleyin.','Hesabınız silindi.'],
    pl: ['Usuń konto','Usuwa konto, ranking, zdjęcia, znajomych i postęp na tym urządzeniu. Powtórki są usuwane; rywalom pozostają tylko anonimowe wyniki. Nie można tego cofnąć. Konto Google i kopie na innych urządzeniach nie są usuwane.','Wpisz DELETE, aby potwierdzić','Usuń trwale','Anuluj','Zakończ partię lub zapis i spróbuj ponownie.','Usunięcie nie zostało potwierdzone. Sprawdź połączenie i ponów próbę. Starszy serwer może nie obsługiwać usuwania.','Zaloguj się ponownie, aby potwierdzić tożsamość.','Usuwanie. Poczekaj na potwierdzenie.','Konto zostało usunięte.'],
    hi: ['खाता मिटाएँ','खाता, रेटिंग, फ़ोटो, मित्र और इस डिवाइस की प्रगति मिट जाएगी। साझा रीप्ले मिटेंगे; विरोधियों के पास केवल गुमनाम जीत-हार के रिकॉर्ड रहेंगे। इसे वापस नहीं किया जा सकता। आपका Google खाता और दूसरे डिवाइस की प्रतियाँ नहीं मिटेंगी।','पुष्टि के लिए DELETE लिखें','हमेशा के लिए मिटाएँ','रद्द करें','मैच या सेव पूरा होने पर फिर कोशिश करें।','मिटाने की पुष्टि नहीं हुई। कनेक्शन जाँचें और फिर कोशिश करें। पुराने सर्वर में यह सुविधा नहीं हो सकती।','पहचान की पुष्टि के लिए फिर लॉग इन करें।','मिटाया जा रहा है। पुष्टि का इंतज़ार करें।','आपका खाता मिटा दिया गया है।'],
    pt: ['Excluir conta','Exclui conta, classificação, fotos, amigos e progresso neste dispositivo. Replays compartilhados são apagados; adversários mantêm apenas resultados anônimos. Não é possível desfazer. Sua conta Google e cópias em outros dispositivos não são excluídas.','Digite DELETE para confirmar','Excluir permanentemente','Cancelar','Termine a partida ou o salvamento e tente novamente.','A exclusão não foi confirmada. Verifique a conexão e tente novamente. Servidores antigos podem não oferecer esta opção.','Entre novamente para confirmar sua identidade.','Excluindo. Aguarde a confirmação.','Sua conta foi excluída.'],
    ta: ['கணக்கை நீக்கு','கணக்கு, மதிப்பீடு, படங்கள், நண்பர்கள் மற்றும் இந்தச் சாதனத்தின் முன்னேற்றம் நீக்கப்படும். பகிரப்பட்ட மறுஒளிபரப்புகள் நீக்கப்படும்; எதிராளிகளிடம் பெயரில்லாத வெற்றி தோல்விப் பதிவுகள் மட்டும் இருக்கும். மீட்டெடுக்க முடியாது. Google கணக்கும் மற்ற சாதனங்களின் நகல்களும் நீக்கப்படாது.','உறுதிசெய்ய DELETE என உள்ளிடவும்','நிரந்தரமாக நீக்கு','ரத்து','ஆட்டம் அல்லது சேமிப்பு முடிந்ததும் மீண்டும் முயலவும்.','நீக்கம் உறுதிசெய்யப்படவில்லை. இணைப்பைச் சரிபார்த்து மீண்டும் முயலவும். பழைய சேவையகம் இதை ஆதரிக்காமல் இருக்கலாம்.','அடையாளத்தை உறுதிசெய்ய மீண்டும் உள்நுழையவும்.','நீக்கப்படுகிறது. உறுதிப்படுத்தலுக்காகக் காத்திருக்கவும்.','உங்கள் கணக்கு நீக்கப்பட்டது.'],
};
export const accountDeletionText = (lang: Language) => {
    const [title,scope,confirmation,action,cancel,busy,unavailable,reauthenticate,working,done] = copy[lang] ?? copy.en;
    return {title,scope,confirmation,action,cancel,busy,unavailable,reauthenticate,working,done,cleanupWarning:cleanupWarning[lang]??cleanupWarning.en};
};
