import { additional } from './additional';

const lessons = {
    tr: ['Beyaz taşı seçip ışıklı kareye götürün. Çapraz hareket onu fil veya vezirle sınırlar.','Güzel! Hareket, olası kimlikleri daraltır.','Siyah taşı seçip beyaz taşı alın. İki kare düz hareket, kale veya vezir demektir.','Taş alındı! Kimliği kesinleşmeden de bir taş alınabilir.','Yeni beyaz taşı ışıklı kareye götürün. L şeklinde yalnızca at hareket eder.','At ortaya çıktı! Tek olasılık kaldığında kimlik kesinleşir.','İlk siyah taşı çapraz hareket ettirerek beyaz atı alın.','Hem düz hem çapraz hareket eden taş vezirdir. Tek vezir olduğundan diğer siyah taş hareket etmeden kale olarak belirlenir!'],
    pl: ['Wybierz białą figurę i przenieś ją na podświetlone pole. Ruch po przekątnej oznacza gońca lub hetmana.','Dobrze! Ruch zawęża możliwe tożsamości.','Wybierz czarną figurę i zbij białą. Dwa pola prosto oznaczają wieżę lub hetmana.','Figura zbita! Można bić także figury o nieznanej tożsamości.','Przenieś nową białą figurę na podświetlone pole. Tylko skoczek porusza się w kształcie L.','Skoczek ujawniony! Jedna możliwość oznacza pewną tożsamość.','Przesuń pierwszą czarną figurę po przekątnej, aby zbić białego skoczka.','Figura ruszająca się prosto i po przekątnej to hetman. Ponieważ hetman jest jeden, druga czarna figura okazuje się wieżą bez ruchu!'],
    pt: ['Selecione a peça branca e mova-a para a casa iluminada. A diagonal limita sua identidade a bispo ou dama.','Muito bem! O movimento reduz as identidades possíveis.','Selecione a peça preta e capture a branca. Duas casas em linha reta indicam torre ou dama.','Peça capturada! É possível capturar antes de revelar a identidade.','Mova a nova peça branca para a casa iluminada. Apenas o cavalo se move em L.','O cavalo foi revelado! Uma única possibilidade confirma a identidade.','Mova a primeira peça preta na diagonal para capturar o cavalo branco.','Mover-se em linha reta e na diagonal revela a dama. Como só existe uma dama, a outra peça preta é identificada como torre sem se mover!'],
    hi: ['सफ़ेद मोहरा चुनकर चमकते खाने पर ले जाएँ। तिरछी चाल से वह ऊँट या वज़ीर हो सकता है।','बहुत अच्छा! चाल संभावित पहचानों को घटाती है।','काला मोहरा चुनकर सफ़ेद मोहरा मारें। दो खाने सीधी चाल का अर्थ हाथी या वज़ीर है।','मोहरा मारा गया! पहचान तय होने से पहले भी मोहरा मारा जा सकता है।','नया सफ़ेद मोहरा चमकते खाने पर ले जाएँ। केवल घोड़ा एल आकार में चलता है।','घोड़े की पहचान तय हुई! एक संभावना बचने पर पहचान निश्चित होती है।','पहले काले मोहरे को तिरछा चलाकर सफ़ेद घोड़ा मारें।','सीधा और तिरछा चलने वाला मोहरा वज़ीर है। केवल एक वज़ीर होने से दूसरा काला मोहरा बिना चले ही हाथी सिद्ध होता है!'],
    ta: ['வெள்ளைக் காயைத் தேர்ந்தெடுத்து ஒளிரும் கட்டத்திற்கு நகர்த்துங்கள். குறுக்கு நகர்வு மந்திரி அல்லது ராணியைக் குறிக்கும்.','நன்று! நகர்வு சாத்தியமான அடையாளங்களைக் குறைக்கிறது.','கருப்புக் காயைத் தேர்ந்தெடுத்து வெள்ளைக் காயை வெட்டுங்கள். இரண்டு கட்டங்கள் நேராக நகர்வது கோட்டை அல்லது ராணியைக் குறிக்கும்.','காய் வெட்டப்பட்டது! அடையாளம் உறுதியாகும் முன்பும் காயை வெட்டலாம்.','புதிய வெள்ளைக் காயை ஒளிரும் கட்டத்திற்கு நகர்த்துங்கள். குதிரை மட்டுமே எல் வடிவத்தில் நகரும்.','குதிரை வெளிப்பட்டது! ஒரு சாத்தியம் மட்டுமே இருந்தால் அடையாளம் உறுதியாகும்.','முதல் கருப்புக் காயைக் குறுக்காக நகர்த்தி வெள்ளைக் குதிரையை வெட்டுங்கள்.','நேராகவும் குறுக்காகவும் நகரும் காய் ராணி. ஒரே ராணி இருப்பதால் மற்ற கருப்புக் காய் நகராமலேயே கோட்டை எனத் தெரிகிறது!'],
};
export const additionalTutorial = Object.fromEntries(Object.entries(lessons).map(([code, lines]) => {
    const t = additional[code as keyof typeof additional];
    return [code, { play:t.play, next:t.next, close:t.back, title:t.rulesButton,
        steps:[lines[0],lines[0],lines[1],lines[2],lines[2],lines[3],lines[4],lines[4],lines[5],lines[6],lines[6],lines[7]] }];
})) as Record<keyof typeof additional, {play:string;next:string;close:string;title:string;steps:string[]}>;
