import type { Language } from './dict';
import { championshipReward } from '../config/championshipRewards';
import { championshipName } from './championshipText';
export const campaignKeys = ['title','intro','challenge','locked','cleared','rewards','equip','equipped','standard','win','loss','draw','next','retry','back','noHints','quick','local','saveError','champion','round','board','piece','white','black'] as const;
const keys = campaignKeys;
type Key = typeof keys[number];
type TranslatedTuple<T extends readonly unknown[]> = {readonly [K in keyof T]:string};
const copy: Record<Language, TranslatedTuple<typeof keys>> = {
 en:['Campaign','Four rounds. Four rivals. Earn your crown.','Challenge','Locked','Cleared','Collection','Equip','Equipped','Original','Victory','Try again. Your unlocks are safe.','Draw','Next round','Rematch','Back','No hints','Win within 20 of your moves','Progress is saved on this device. Cosmetics do not affect strength.','Could not save. Keep this page open to retain progress.','Tournament champion','Round','Board','Piece material','White · first','Black · second'],
 ja:['キャンペーン','4回戦、4人のライバル。王座へ続く挑戦。','挑戦する','未解放','クリア','コレクション','装備する','装備中','オリジナル','勝利','もう一度挑戦。解放済みの報酬は残ります。','引き分け','次のラウンド','再挑戦','戻る','ヒントなし','自分の20手以内で勝利','進行はこの端末に保存されます。外観で強さは変わりません。','保存できませんでした。進行を保つにはこの画面を閉じないでください。','トーナメント制覇','ラウンド','盤面','駒の材質','白・先手','黒・後手'],
 zh:['战役','四轮，四位对手。向王座进发。','挑战','未解锁','已通关','收藏','装备','已装备','原版','胜利','再试一次。已解锁奖励会保留。','和棋','下一轮','再次挑战','返回','不使用提示','在自己的20步内获胜','进度保存在此设备。外观不影响实力。','无法保存。请保持此页面打开以保留进度。','锦标赛冠军','轮次','棋盘','棋子材质','白方·先手','黑方·后手'],
 ru:['Кампания','Четыре раунда. Четыре соперника. Путь к короне.','Вызвать','Закрыто','Пройдено','Коллекция','Выбрать','Выбрано','Оригинал','Победа','Попробуйте снова. Награды сохраняются.','Ничья','Следующий раунд','Реванш','Назад','Без подсказок','Победа за 20 своих ходов','Прогресс хранится на устройстве. Облик не влияет на силу.','Не удалось сохранить. Не закрывайте страницу.','Чемпион турнира','Раунд','Доска','Материал фигур','Белые · первый ход','Чёрные · второй ход'],
 fr:['Campagne','Quatre manches. Quatre rivaux. À vous la couronne.','Défier','Verrouillé','Terminé','Collection','Équiper','Équipé','Original','Victoire','Réessayez. Vos récompenses restent acquises.','Nulle','Manche suivante','Rejouer','Retour','Sans indice','Gagner en 20 coups personnels','Progression enregistrée sur cet appareil. Les apparences ne changent pas la force.','Échec de sauvegarde. Gardez cette page ouverte.','Champion du tournoi','Manche','Échiquier','Matériau des pièces','Blancs · premier','Noirs · second'],
 de:['Kampagne','Vier Runden. Vier Rivalen. Dein Weg zur Krone.','Herausfordern','Gesperrt','Geschafft','Sammlung','Ausrüsten','Ausgerüstet','Original','Sieg','Versuche es erneut. Freigeschaltete Belohnungen bleiben.','Remis','Nächste Runde','Revanche','Zurück','Ohne Hinweise','In 20 eigenen Zügen gewinnen','Fortschritt wird auf diesem Gerät gespeichert. Designs ändern die Stärke nicht.','Speichern fehlgeschlagen. Lass diese Seite geöffnet.','Turniersieger','Runde','Brett','Figurenmaterial','Weiß · erster Zug','Schwarz · zweiter Zug'],
 es:['Campaña','Cuatro rondas. Cuatro rivales. Gana la corona.','Desafiar','Bloqueado','Superado','Colección','Equipar','Equipado','Original','Victoria','Inténtalo de nuevo. Conservas tus recompensas.','Tablas','Siguiente ronda','Revancha','Volver','Sin pistas','Gana en 20 movimientos propios','El progreso se guarda en este dispositivo. El aspecto no cambia la fuerza.','No se pudo guardar. Mantén esta página abierta.','Campeón del torneo','Ronda','Tablero','Material de piezas','Blancas · primero','Negras · segundo'],
 tr:['Sefer','Dört tur. Dört rakip. Tacı kazan.','Meydan oku','Kilitli','Tamamlandı','Koleksiyon','Kuşan','Kuşanıldı','Orijinal','Zafer','Tekrar dene. Açılan ödüller sende kalır.','Berabere','Sonraki tur','Yeniden oyna','Geri','İpucu olmadan','Kendi 20 hamlen içinde kazan','İlerleme bu cihazda saklanır. Görünümler gücü değiştirmez.','Kaydedilemedi. Bu sayfayı açık tut.','Turnuva şampiyonu','Tur','Tahta','Taş malzemesi','Beyaz · ilk','Siyah · ikinci'],
 pl:['Kampania','Cztery rundy. Czterech rywali. Zdobądź koronę.','Rzuć wyzwanie','Zablokowane','Ukończono','Kolekcja','Załóż','Wybrane','Oryginalny','Zwycięstwo','Spróbuj ponownie. Odblokowane nagrody pozostają.','Remis','Następna runda','Rewanż','Wróć','Bez podpowiedzi','Wygraj w 20 własnych ruchach','Postęp zapisuje się na tym urządzeniu. Wygląd nie zmienia siły.','Nie udało się zapisać. Nie zamykaj tej strony.','Mistrz turnieju','Runda','Szachownica','Materiał figur','Białe · pierwsze','Czarne · drugie'],
 hi:['अभियान','चार दौर। चार प्रतिद्वंद्वी। ताज जीतें।','चुनौती दें','बंद','पूरा','संग्रह','चुनें','चुना हुआ','मूल','जीत','फिर कोशिश करें। खुले पुरस्कार बने रहेंगे।','ड्रॉ','अगला दौर','फिर खेलें','वापस','बिना संकेत','अपनी 20 चालों में जीतें','प्रगति इस उपकरण पर सहेजी जाती है। रूप से ताकत नहीं बदलती।','सहेज नहीं सके। यह पृष्ठ खुला रखें।','टूर्नामेंट विजेता','दौर','बोर्ड','मोहरे की सामग्री','सफेद · पहले','काला · दूसरे'],
 pt:['Campanha','Quatro rodadas. Quatro rivais. Conquiste a coroa.','Desafiar','Bloqueado','Concluído','Coleção','Equipar','Equipado','Original','Vitória','Tente novamente. Suas recompensas continuam liberadas.','Empate','Próxima rodada','Revanche','Voltar','Sem dicas','Vença em 20 movimentos seus','O progresso é salvo neste dispositivo. A aparência não muda a força.','Não foi possível salvar. Mantenha esta página aberta.','Campeão do torneio','Rodada','Tabuleiro','Material das peças','Brancas · primeiro','Pretas · segundo'],
 ta:['பயணம்','நான்கு சுற்றுகள். நான்கு எதிரிகள். மகுடத்தை வெல்லுங்கள்.','சவால் விடு','திறக்கப்படவில்லை','முடிந்தது','சேகரிப்பு','பயன்படுத்து','பயன்பாட்டில்','அசல்','வெற்றி','மீண்டும் முயலுங்கள். திறந்த பரிசுகள் உங்களிடமே இருக்கும்.','சமநிலை','அடுத்த சுற்று','மீண்டும் ஆடு','திரும்பு','குறிப்பு இல்லாமல்','உங்கள் 20 நகர்வுகளுக்குள் வெற்றி','முன்னேற்றம் இந்தச் சாதனத்தில் சேமிக்கப்படும். தோற்றம் வலிமையை மாற்றாது.','சேமிக்க முடியவில்லை. இந்தப் பக்கத்தைத் திறந்தே வைத்திருங்கள்.','போட்டி சாம்பியன்','சுற்று','பலகை','காய்களின் பொருள்','வெள்ளை · முதலில்','கருப்பு · அடுத்து'],
};
const profiles: Record<Language, readonly string[]> = {
 en:['A patient opening rival. Learn to narrow possibilities.','An attacker who values material and forward pressure.','A guardian who protects pieces and preserves possibilities.','The final rival. Balanced judgment with deeper search.'],
 ja:['可能性を絞る基礎を試す、入門の相手。','駒の価値と前進を重視する攻撃型。','駒の安全と候補の柔軟性を守る慎重型。','最終ボス。均衡の取れた評価と深い探索。'],
 zh:['入门对手，练习缩小候选范围。','重视子力与推进的攻击型。','重视棋子安全与候选灵活性的守护者。','最终对手：均衡判断与更深搜索。'],
 ru:['Первый соперник: учитесь сужать варианты.','Атакует, ценит материал и продвижение.','Защищает фигуры и сохраняет варианты.','Финальный соперник: баланс и глубокий поиск.'],
 fr:['Un premier rival pour apprendre à réduire les possibilités.','Valorise le matériel et la progression.','Protège les pièces et préserve les possibilités.','Le rival final : équilibre et recherche approfondie.'],
 de:['Der erste Rivale: Möglichkeiten eingrenzen lernen.','Angreifer mit Fokus auf Material und Vorstoß.','Schützt Figuren und bewahrt Möglichkeiten.','Der letzte Rivale: ausgewogen und tiefer suchend.'],
 es:['El primer rival: aprende a reducir posibilidades.','Ataca priorizando material y avance.','Protege las piezas y conserva posibilidades.','Rival final: equilibrio y búsqueda profunda.'],
 tr:['İlk rakip: olasılıkları daraltmayı öğren.','Taş değerini ve ilerlemeyi önemseyen saldırgan.','Taşları korur ve olasılıkları saklar.','Son rakip: dengeli değerlendirme ve derin arama.'],
 pl:['Pierwszy rywal: naucz się zawężać możliwości.','Atakuje, ceni materiał i postęp.','Chroni figury i zachowuje możliwości.','Ostatni rywal: równowaga i głębsze szukanie.'],
 hi:['पहला प्रतिद्वंद्वी: संभावनाएँ सीमित करना सीखें।','मोहरे के मूल्य और आगे बढ़ने पर जोर देता है।','मोहरों की सुरक्षा और संभावनाओं को बचाता है।','अंतिम प्रतिद्वंद्वी: संतुलित मूल्यांकन और गहरी खोज।'],
 pt:['Primeiro rival: aprenda a reduzir possibilidades.','Ataca valorizando material e avanço.','Protege as peças e preserva possibilidades.','Rival final: equilíbrio e busca mais profunda.'],
 ta:['முதல் எதிரி: சாத்தியங்களைக் குறைக்கக் கற்றுக்கொள்ளுங்கள்.','காய்களின் மதிப்பையும் முன்னேற்றத்தையும் நாடும் தாக்குதல் வீரர்.','காய்களின் பாதுகாப்பையும் சாத்தியங்களையும் காப்பவர்.','இறுதி எதிரி: சமமான மதிப்பீடும் ஆழமான தேடலும்.'],
};
const cosmetics: Record<Language, readonly string[]> = {
 en:['Slate','Copper','Obsidian','Jade'],ja:['青石','銅','黒曜石','翡翠'],zh:['青石','铜','黑曜石','翡翠'],ru:['Сланец','Медь','Обсидиан','Нефрит'],fr:['Ardoise','Cuivre','Obsidienne','Jade'],de:['Schiefer','Kupfer','Obsidian','Jade'],es:['Pizarra','Cobre','Obsidiana','Jade'],tr:['Arduvaz','Bakır','Obsidyen','Yeşim'],pl:['Łupek','Miedź','Obsydian','Jadeit'],hi:['स्लेट','ताँबा','ओब्सीडियन','जेड'],pt:['Ardósia','Cobre','Obsidiana','Jade'],ta:['நீலக்கல்','செம்பு','கருங்கண்ணாடிக் கல்','பச்சைக்கல்'],
};
export const campaignText = (lang:Language,key:Key) => copy[lang][keys.indexOf(key)];
export const bossDescription = (lang:Language,index:number) => profiles[lang][index];
export const rewardName = (lang:Language,id:string) => {
    const reward=championshipReward(id);
    return reward ? championshipName(lang,reward) : id === 'standard' ? campaignText(lang,'standard') : cosmetics[lang][['slate','copper','obsidian','jade'].indexOf(id)];
};
export const campaignTranslationCount = (lang:Language) => copy[lang].length;
