import type {Language} from './dict';
const rows:Record<Language,readonly string[]>={
    en:['Cloud save','Syncing…','Saved to your account','Changes waiting to sync','Could not sync. Local progress is preserved.','Try again','Import earlier progress from this device','Assign the earlier device save to this account? It cannot be assigned to a different account later.','Import','Progress and appearance are saved per account. Check cloud-save status in Settings before changing devices.'],
    ja:['クラウド保存','同期中…','アカウントに保存済み','変更の同期待ち','同期できませんでした。端末の進行は保持しています。','再試行','この端末の以前の進行を引き継ぐ','以前の端末データをこのアカウントへ引き継ぎますか？ 後から別のアカウントには引き継げません。','引き継ぐ','進行と外観はアカウント別に保存します。端末を変える前に設定でクラウド保存の状態を確認してください。'],
    zh:['云端存档','同步中…','已保存至账号','等待同步更改','同步失败，本机进度已保留。','重试','导入本机以前的进度','将本机旧存档归属此账号？之后不能再归属其他账号。','导入','进度和外观按账号保存。换设备前请在设置中确认云端保存状态。'],
    ru:['Облачное сохранение','Синхронизация…','Сохранено в аккаунте','Изменения ожидают синхронизации','Не удалось синхронизировать. Локальный прогресс сохранён.','Повторить','Импортировать прежний прогресс устройства','Привязать прежнее сохранение к этому аккаунту? Позже его нельзя будет привязать к другому.','Импорт','Прогресс и оформление сохраняются для каждого аккаунта. Перед сменой устройства проверьте облачное сохранение в настройках.'],
    fr:['Sauvegarde cloud','Synchronisation…','Enregistré dans le compte','Modifications en attente','Échec de synchronisation. Progression locale conservée.','Réessayer','Importer la progression précédente de cet appareil','Attribuer l’ancienne sauvegarde à ce compte ? Elle ne pourra plus être attribuée à un autre.','Importer','Progression et apparence sont enregistrées par compte. Vérifiez la sauvegarde cloud dans les réglages avant de changer d’appareil.'],
    de:['Cloud-Spielstand','Synchronisierung…','Im Konto gespeichert','Änderungen warten auf Synchronisierung','Synchronisierung fehlgeschlagen. Lokaler Fortschritt bleibt erhalten.','Erneut versuchen','Früheren Fortschritt dieses Geräts importieren','Alten Spielstand diesem Konto zuweisen? Eine spätere Zuweisung an ein anderes Konto ist nicht möglich.','Importieren','Fortschritt und Aussehen werden pro Konto gespeichert. Prüfe vor dem Gerätewechsel den Cloud-Status in den Einstellungen.'],
    es:['Guardado en la nube','Sincronizando…','Guardado en la cuenta','Cambios pendientes','No se pudo sincronizar. Se conserva el progreso local.','Reintentar','Importar el progreso anterior del dispositivo','¿Asignar el guardado anterior a esta cuenta? No podrá asignarse a otra después.','Importar','Progreso y apariencia se guardan por cuenta. Comprueba el estado en Ajustes antes de cambiar de dispositivo.'],
    tr:['Bulut kaydı','Eşitleniyor…','Hesaba kaydedildi','Değişiklikler eşitleme bekliyor','Eşitlenemedi. Yerel ilerleme korundu.','Yeniden dene','Cihazın önceki ilerlemesini içe aktar','Önceki kayıt bu hesaba atansın mı? Daha sonra başka hesaba atanamaz.','İçe aktar','İlerleme ve görünüm hesap başına kaydedilir. Cihaz değiştirmeden önce Ayarlar’da bulut durumunu kontrol edin.'],
    pl:['Zapis w chmurze','Synchronizacja…','Zapisano na koncie','Zmiany czekają na synchronizację','Synchronizacja nie powiodła się. Lokalny postęp zachowany.','Ponów','Importuj wcześniejszy postęp urządzenia','Przypisać stary zapis do tego konta? Później nie będzie można przypisać go do innego.','Importuj','Postęp i wygląd są zapisywane osobno dla kont. Przed zmianą urządzenia sprawdź chmurę w ustawieniach.'],
    hi:['क्लाउड सेव','सिंक हो रहा है…','खाते में सहेजा गया','बदलाव सिंक होने बाकी हैं','सिंक नहीं हुआ। स्थानीय प्रगति सुरक्षित है।','फिर कोशिश करें','इस डिवाइस की पिछली प्रगति लाएँ','पुराना सेव इस खाते से जोड़ें? बाद में इसे दूसरे खाते से नहीं जोड़ सकते।','लाएँ','प्रगति और रूप हर खाते के लिए अलग सहेजे जाते हैं। डिवाइस बदलने से पहले सेटिंग में क्लाउड सेव जाँचें।'],
    pt:['Salvar na nuvem','Sincronizando…','Salvo na conta','Alterações aguardando sincronização','Não foi possível sincronizar. Progresso local preservado.','Tentar novamente','Importar o progresso anterior deste dispositivo','Atribuir o salvamento anterior a esta conta? Depois não poderá ser atribuído a outra.','Importar','Progresso e aparência são salvos por conta. Confira o estado da nuvem nas configurações antes de trocar de dispositivo.'],
    ta:['கிளவுட் சேமிப்பு','ஒத்திசைக்கிறது…','கணக்கில் சேமிக்கப்பட்டது','மாற்றங்கள் ஒத்திசைவுக்குக் காத்திருக்கின்றன','ஒத்திசைக்க முடியவில்லை. உள்ளூர் முன்னேற்றம் பாதுகாக்கப்பட்டது.','மீண்டும் முயலவும்','இந்தச் சாதனத்தின் முந்தைய முன்னேற்றத்தை இறக்குமதி செய்க','முந்தைய சேமிப்பை இக்கணக்குடன் இணைக்கவா? பின்னர் வேறு கணக்குடன் இணைக்க முடியாது.','இறக்குமதி','முன்னேற்றமும் தோற்றமும் கணக்குவாரியாகச் சேமிக்கப்படும். சாதனம் மாற்றும் முன் அமைப்புகளில் கிளவுட் நிலையைச் சரிபார்க்கவும்.'],
};
const keys=['title','loading','saved','pending','error','retry','legacy','confirm','import','help'] as const;
export const cloudText=(lang:Language,key:typeof keys[number])=>rows[lang][keys.indexOf(key)];
