import type { Language } from './dict';
const keys = ['title', 'help', 'locked', 'acquired', 'notAcquired', 'settingsOnly', 'previewOnly', 'classic', 'marble', 'neon', 'choose'] as const;
const text: Record<Language, readonly string[]> = {
    en: ['Your collection', 'Choose acquired designs for your next match.', 'Designs are fixed during a match. You can change them after returning to the menu.', 'Acquired', 'Not acquired', 'Select acquired rewards in Settings.', 'Preview only. Your selections will not change.', 'Classic', 'Marble', 'Neon', 'Selected'],
    ja: ['コレクション設定', '獲得したデザインを、次の対局に。', '対局中のデザインは固定です。メニューに戻ると変更できます。', '獲得済み', '未獲得', '獲得した報酬は設定から選択できます。', 'プレビューのみ。選択中のデザインは変わりません。', 'クラシック', 'マーブル', 'ネオン', '選択中'],
    zh: ['收藏设置', '为下一局选择已获得的设计。', '对局中设计固定，返回菜单后可更改。', '已获得', '未获得', '在设置中选择已获得的奖励。', '仅预览，不会更改当前选择。', '经典', '大理石', '霓虹', '已选择'],
    ru: ['Настройки коллекции', 'Выберите полученные дизайны для следующей партии.', 'Во время партии дизайн закреплён. Измените его после возврата в меню.', 'Получено', 'Не получено', 'Выбирайте полученные награды в настройках.', 'Только просмотр. Выбранный дизайн не изменится.', 'Классика', 'Мрамор', 'Неон', 'Выбрано'],
    fr: ['Votre collection', 'Choisissez vos designs acquis pour la prochaine partie.', 'Les designs sont fixes pendant la partie. Modifiez-les depuis le menu.', 'Acquis', 'Non acquis', 'Sélectionnez les récompenses acquises dans les paramètres.', 'Aperçu uniquement. Vos choix ne changent pas.', 'Classique', 'Marbre', 'Néon', 'Sélectionné'],
    de: ['Deine Sammlung', 'Wähle erhaltene Designs für die nächste Partie.', 'Designs bleiben während der Partie unverändert. Ändere sie anschließend im Menü.', 'Erhalten', 'Nicht erhalten', 'Erhaltene Belohnungen wählst du in den Einstellungen.', 'Nur Vorschau. Deine Auswahl bleibt unverändert.', 'Klassisch', 'Marmor', 'Neon', 'Ausgewählt'],
    es: ['Tu colección', 'Elige diseños obtenidos para tu próxima partida.', 'El diseño queda fijo durante la partida. Cámbialo al volver al menú.', 'Obtenido', 'No obtenido', 'Selecciona las recompensas obtenidas en Ajustes.', 'Solo vista previa. Tu selección no cambia.', 'Clásico', 'Mármol', 'Neón', 'Seleccionado'],
    tr: ['Koleksiyon ayarları', 'Sonraki maç için kazanılmış tasarımları seç.', 'Maç sırasında tasarımlar sabittir. Menüye döndükten sonra değiştirilebilir.', 'Kazanıldı', 'Kazanılmadı', 'Kazanılan ödülleri Ayarlar bölümünden seç.', 'Yalnızca önizleme. Seçimlerin değişmez.', 'Klasik', 'Mermer', 'Neon', 'Seçili'],
    pl: ['Twoja kolekcja', 'Wybierz zdobyte wzory do następnej partii.', 'Wygląd jest stały podczas partii. Zmień go po powrocie do menu.', 'Zdobyto', 'Nie zdobyto', 'Zdobyte nagrody wybierzesz w ustawieniach.', 'Tylko podgląd. Twój wybór się nie zmienia.', 'Klasyczny', 'Marmur', 'Neon', 'Wybrano'],
    hi: ['संग्रह सेटिंग', 'अगली बाज़ी के लिए प्राप्त डिज़ाइन चुनें।', 'बाज़ी के दौरान डिज़ाइन स्थिर रहता है। मेन्यू में लौटकर इसे बदलें।', 'प्राप्त', 'अप्राप्त', 'प्राप्त पुरस्कार सेटिंग में चुनें।', 'केवल पूर्वावलोकन। आपका चयन नहीं बदलेगा।', 'क्लासिक', 'संगमरमर', 'नियॉन', 'चयनित'],
    pt: ['Sua coleção', 'Escolha designs obtidos para a próxima partida.', 'Os designs ficam fixos durante a partida. Altere-os após voltar ao menu.', 'Obtido', 'Não obtido', 'Selecione as recompensas obtidas nas configurações.', 'Apenas prévia. Suas escolhas não mudam.', 'Clássico', 'Mármore', 'Neon', 'Selecionado'],
    ta: ['சேகரிப்பு அமைப்புகள்', 'அடுத்த ஆட்டத்திற்குப் பெற்ற வடிவமைப்புகளைத் தேர்ந்தெடுக்கவும்.', 'ஆட்டத்தின் போது வடிவமைப்பு மாறாது. மெனுவிற்குத் திரும்பியபின் மாற்றலாம்.', 'பெறப்பட்டது', 'பெறப்படவில்லை', 'பெற்ற பரிசுகளை அமைப்புகளில் தேர்ந்தெடுக்கவும்.', 'முன்னோட்டம் மட்டும். தேர்வுகள் மாறாது.', 'கிளாசிக்', 'பளிங்கு', 'நியான்', 'தேர்ந்தெடுக்கப்பட்டது']
};
export const cosmeticsSettingsText = (lang: Language, key: typeof keys[number]) => (text[lang] ?? text.en)[keys.indexOf(key)];
export const cosmeticsSettingsKeys = keys;
