import type { Language } from './dict';

export const crownNavigationKeys = ['challenge','boards','pieces','frames','effects','music','nextStage','firstClear','improveStars','journey','details','page','chooseSide','entryError','lockedGoal','completeGoal','castleRoute','withQube','kingBoss','insideCastle'] as const;
type Copy = { [K in typeof crownNavigationKeys[number]]: string };
const rows: Record<Language, readonly string[]> = {
 en:['Challenge','Boards','Pieces','Frames','Effects','Music','Next stage','First-clear reward','Improve your stars','Your journey','How it works','Page','Play as','Could not prepare the game. Please try again.','Clear the preceding stages to challenge this opponent.','All stages cleared. Replay to improve your stars.',"Castle route","With QUBE","King boss","Advance through the castle with QUBE. Defeat stronger chess-piece rivals on your way to the King."],
 ja:['チャレンジ','盤面','駒','フレーム','エフェクト','BGM','次のステージ','初勝利の報酬','星を増やそう','これまでの道のり','遊び方','ページ','プレイする側','対局の準備ができませんでした。もう一度お試しください。','前のステージをクリアすると挑戦できます。','全ステージクリア。再挑戦して星を増やそう。',"城内の道のり","QUBEと一緒に","キングのボス","QUBEと城の中を進もう。チェスの駒の強敵たちを倒し、最後のキングに挑もう。"],
 zh:['挑战','棋盘','棋子','头像框','特效','音乐','下一关','首胜奖励','争取更多星星','挑战之路','玩法说明','页','执棋方','无法准备对局，请重试。','通关前面的关卡即可挑战此对手。','已通关全部关卡，再次挑战以获得更多星星。',"城堡之路","与QUBE同行","国王首领","与QUBE一同深入城堡，击败更强的棋子对手，最后挑战国王。"],
 ru:['Испытание','Доски','Фигуры','Рамки','Эффекты','Музыка','Следующий этап','Награда за первый успех','Улучшите оценку','Ваш путь','Как играть','Страница','Играть за','Не удалось подготовить партию. Попробуйте снова.','Пройдите предыдущие этапы, чтобы вызвать соперника.','Все этапы пройдены. Играйте снова ради звёзд.',"Путь по замку","Вместе с QUBE","Король-босс","Пройдите замок вместе с QUBE. Побеждайте всё более сильные шахматные фигуры на пути к Королю."],
 fr:['Défi','Échiquiers','Pièces','Cadres','Effets','Musique','Étape suivante','Récompense de première victoire','Gagnez plus d’étoiles','Votre parcours','Comment jouer','Page','Jouer avec','Impossible de préparer la partie. Réessayez.','Terminez les étapes précédentes pour défier cet adversaire.','Toutes les étapes sont terminées. Rejouez pour gagner des étoiles.',"Parcours du château","Avec QUBE","Boss Roi","Parcourez le château avec QUBE. Affrontez des pièces toujours plus fortes jusqu’au Roi."],
 de:['Herausforderung','Bretter','Figuren','Rahmen','Effekte','Musik','Nächste Stufe','Belohnung für den ersten Sieg','Mehr Sterne sammeln','Dein Weg','Spielanleitung','Seite','Spielen als','Die Partie konnte nicht vorbereitet werden. Bitte erneut versuchen.','Schließe die vorherigen Stufen ab, um diesen Gegner herauszufordern.','Alle Stufen geschafft. Spiele erneut, um mehr Sterne zu sammeln.',"Weg durch die Burg","Mit QUBE","Königsboss","Ziehe mit QUBE durch die Burg. Besiege immer stärkere Schachfiguren auf dem Weg zum König."],
 es:['Desafío','Tableros','Piezas','Marcos','Efectos','Música','Siguiente etapa','Premio por primera victoria','Consigue más estrellas','Tu recorrido','Cómo jugar','Página','Jugar con','No se pudo preparar la partida. Inténtalo de nuevo.','Completa las etapas anteriores para desafiar a este rival.','Todas las etapas completadas. Vuelve a jugar para ganar estrellas.',"Ruta del castillo","Con QUBE","Jefe Rey","Avanza por el castillo con QUBE. Derrota a rivales de ajedrez cada vez más fuertes hasta llegar al Rey."],
 tr:['Mücadele','Tahtalar','Taşlar','Çerçeveler','Efektler','Müzik','Sonraki aşama','İlk galibiyet ödülü','Daha çok yıldız kazan','Yolculuğun','Nasıl oynanır','Sayfa','Oynayacağın taraf','Maç hazırlanamadı. Lütfen tekrar dene.','Bu rakiple oynamak için önceki aşamaları tamamla.','Tüm aşamalar tamamlandı. Daha çok yıldız için tekrar oyna.',"Kale yolu","QUBE ile","Şah patronu","QUBE ile kalede ilerle. Şaha ulaşana kadar giderek güçlenen satranç rakiplerini yen."],
 pl:['Wyzwanie','Szachownice','Figury','Ramki','Efekty','Muzyka','Następny etap','Nagroda za pierwszą wygraną','Zdobądź więcej gwiazd','Twoja droga','Jak grać','Strona','Graj jako','Nie udało się przygotować partii. Spróbuj ponownie.','Ukończ poprzednie etapy, aby wyzwać tego rywala.','Wszystkie etapy ukończone. Graj ponownie po więcej gwiazd.',"Droga przez zamek","Razem z QUBE","Boss Król","Przemierzaj zamek z QUBE. Pokonuj coraz silniejsze figury szachowe w drodze do Króla."],
 hi:['चुनौती','बोर्ड','मोहरे','फ़्रेम','प्रभाव','संगीत','अगला स्तर','पहली जीत का पुरस्कार','और सितारे कमाएँ','आपका सफ़र','कैसे खेलें','पृष्ठ','पक्ष चुनें','बाज़ी तैयार नहीं हो सकी। फिर से कोशिश करें।','इस प्रतिद्वंद्वी को चुनौती देने के लिए पिछले स्तर पूरे करें।','सभी स्तर पूरे हुए। और सितारों के लिए फिर खेलें।',"महल का मार्ग","QUBE के साथ","राजा बॉस","QUBE के साथ महल में आगे बढ़ें। राजा तक पहुँचने के लिए अधिक शक्तिशाली शतरंज प्रतिद्वंद्वियों को हराएँ।"],
 pt:['Desafio','Tabuleiros','Peças','Molduras','Efeitos','Música','Próxima etapa','Prêmio da primeira vitória','Ganhe mais estrelas','Sua jornada','Como jogar','Página','Jogar com','Não foi possível preparar a partida. Tente novamente.','Conclua as etapas anteriores para desafiar este rival.','Todas as etapas concluídas. Jogue de novo para ganhar estrelas.',"Rota do castelo","Com QUBE","Chefe Rei","Avance pelo castelo com QUBE. Derrote rivais de xadrez cada vez mais fortes até chegar ao Rei."],
 ta:['சவால்','பலகைகள்','காய்கள்','சட்டகங்கள்','விளைவுகள்','இசை','அடுத்த நிலை','முதல் வெற்றிப் பரிசு','மேலும் நட்சத்திரங்கள் பெறுங்கள்','உங்கள் பயணம்','விளையாடுவது எப்படி','பக்கம்','விளையாடும் தரப்பு','ஆட்டத்தைத் தயாரிக்க முடியவில்லை. மீண்டும் முயலுங்கள்.','இந்த எதிராளியைச் சவால் செய்ய முந்தைய நிலைகளை முடிக்கவும்.','எல்லா நிலைகளும் முடிந்தன. மேலும் நட்சத்திரங்களுக்கு மீண்டும் விளையாடுங்கள்.',"கோட்டைப் பாதை","QUBE உடன்","ராஜா தலைவன்","QUBE உடன் கோட்டைக்குள் முன்னேறுங்கள். மேலும் வலுவான சதுரங்க எதிரிகளை வென்று ராஜாவைச் சந்தியுங்கள்."],
};
// Keeping the key lookup in one place makes missing translations testable.
export const crownNavigationText = (lang: Language, key: keyof Copy) => rows[lang][crownNavigationKeys.indexOf(key)];
export const crownNavigationTranslationCount = (lang: Language) => rows[lang].length;
