import type {Language} from './dict';
import {FOUNDERS_BOARD_ID,FOUNDERS_FRAME_ID,FOUNDERS_PIECE_ID} from '../config/founders';
const keys=['title','frame','board','piece','description','claim','refresh','acquired','preview','account','web','login','preparing','busy','unavailable','ineligible','linked','pending','delivery'] as const;
type Tuple<T extends readonly unknown[]>={readonly [K in keyof T]:string};
const copy:Record<Language,Tuple<typeof keys>>={
 en:['Founders’ Collection','Founders’ Crown','Obsidian & Gold Inlay','Ivory & Onyx · Founders','Google Play pre-registration bonus: three exclusive cosmetics. No gameplay advantage.','Claim / restore free bonus','Check again','Acquired · choose in Appearance','Preview','Linked permanently to this game account:','Claim in the Android app installed from Google Play. Claimed rewards also sync here.','Sign in to receive or restore.','Reward delivery is not enabled yet.','Checking…','Could not verify. Try again later.','No eligible bonus. Check the Google Play account used for pre-registration.','Already linked to another game account.','Google Play is still processing. Try again later.','Reward saved. Play confirmation pending; restore again later.'],
 ja:['ファウンダーズ・コレクション','ファウンダーズ・クラウン','黒曜石と金の象嵌','象牙とオニキス・ファウンダーズ','Google Play事前登録特典の限定装飾3点です。対局の強さには影響しません。','無料特典を受け取る・復元','再確認','獲得済み・外観設定で選択できます','プレビュー','次のゲームアカウントに一度だけ紐付きます：','Google PlayからインストールしたAndroidアプリで受け取れます。受取済みの特典はここにも同期されます。','特典の受け取り・復元にはログインしてください。','特典の配布はまだ有効になっていません。','確認中…','確認できませんでした。時間をおいて再確認してください。','対象の特典が見つかりません。事前登録したGoogle Playアカウントを確認してください。','この特典は別のゲームアカウントで受取済みです。','Google Playで処理中です。後ほど再確認してください。','特典は保存済みです。Playへの完了通知は処理中のため、後ほど復元を再実行してください。'],
 zh:['创始者典藏','创始者王冠','黑曜石与金镶嵌','象牙与缟玛瑙·创始者','Google Play预注册赠礼：三款限定外观，不影响棋力。','免费领取／恢复','重新检查','已获得·在外观设置中选择','预览','将永久绑定到此游戏账号：','请在Google Play安装的Android应用中领取。奖励也会同步到这里。','请登录以领取或恢复。','奖励发放尚未开启。','检查中…','无法验证，请稍后重试。','未找到奖励，请检查预注册的Google Play账号。','已绑定到其他游戏账号。','Google Play正在处理，请稍后重试。','奖励已保存，Play确认处理中，请稍后再次恢复。'],
 ru:['Коллекция основателей','Корона основателя','Обсидиан и золотая инкрустация','Слоновая кость и оникс · Основатели','Бонус предрегистрации Google Play: три облика без игрового преимущества.','Получить / восстановить бесплатно','Проверить снова','Получено · выберите в настройках облика','Просмотр','Навсегда привязывается к аккаунту:','Получите в Android-приложении из Google Play. Награды синхронизируются и здесь.','Войдите для получения или восстановления.','Выдача наград пока не включена.','Проверка…','Не удалось проверить. Повторите позже.','Бонус не найден. Проверьте аккаунт Google Play предрегистрации.','Бонус привязан к другому аккаунту.','Google Play обрабатывает награду. Повторите позже.','Награда сохранена. Подтверждение Play ожидается; повторите восстановление позже.'],
 fr:['Collection des fondateurs','Couronne des fondateurs','Obsidienne et marqueterie d’or','Ivoire et onyx · Fondateurs','Bonus de préinscription Google Play : trois apparences, sans avantage en jeu.','Recevoir / restaurer gratuitement','Vérifier à nouveau','Acquis · à choisir dans Apparence','Aperçu','Associé définitivement à ce compte :','À recevoir dans Android installé depuis Google Play. Les récompenses se synchronisent ici aussi.','Connectez-vous pour recevoir ou restaurer.','La distribution n’est pas encore activée.','Vérification…','Vérification impossible. Réessayez plus tard.','Bonus introuvable. Vérifiez le compte Google Play de préinscription.','Déjà associé à un autre compte.','Google Play traite la récompense. Réessayez plus tard.','Récompense enregistrée. Confirmation Play en attente ; restaurez à nouveau plus tard.'],
 de:['Gründerkollektion','Gründerkrone','Obsidian mit Goldeinlagen','Elfenbein und Onyx · Gründer','Google-Play-Vorregistrierungsbonus: drei Designs ohne Spielvorteil.','Kostenlosen Bonus erhalten / wiederherstellen','Erneut prüfen','Erhalten · unter Aussehen auswählen','Vorschau','Dauerhaft mit diesem Spielkonto verknüpft:','Im Android-Spiel aus Google Play abholen. Belohnungen werden auch hier synchronisiert.','Zum Abholen oder Wiederherstellen anmelden.','Belohnungsausgabe noch nicht aktiviert.','Wird geprüft…','Prüfung nicht möglich. Später erneut versuchen.','Kein Bonus. Prüfe das Google-Play-Konto der Vorregistrierung.','Bereits mit einem anderen Spielkonto verknüpft.','Google Play bearbeitet die Belohnung. Später erneut versuchen.','Belohnung gespeichert. Play-Bestätigung steht aus; später erneut wiederherstellen.'],
 es:['Colección de fundadores','Corona de fundadores','Obsidiana e incrustaciones de oro','Marfil y ónice · Fundadores','Bono de registro previo en Google Play: tres aspectos sin ventaja en las partidas.','Recibir / restaurar gratis','Comprobar de nuevo','Obtenido · seleccionar en Apariencia','Vista previa','Se vinculará permanentemente a esta cuenta:','Recíbelo en Android instalado desde Google Play. Las recompensas también se sincronizan aquí.','Inicia sesión para recibir o restaurar.','La entrega aún no está activada.','Comprobando…','No se pudo verificar. Inténtalo más tarde.','Bono no encontrado. Comprueba la cuenta Google Play del registro previo.','Ya vinculado a otra cuenta.','Google Play está procesando. Inténtalo más tarde.','Recompensa guardada. Confirmación Play pendiente; restaura de nuevo más tarde.'],
 tr:['Kurucular Koleksiyonu','Kurucular Tacı','Obsidyen ve Altın Kakma','Fildişi ve Oniks · Kurucular','Google Play ön kayıt hediyesi: oyun avantajı sağlamayan üç özel görünüm.','Ücretsiz hediyeyi al / geri yükle','Yeniden kontrol et','Kazanıldı · Görünüm ayarlarından seçin','Önizleme','Bu oyun hesabına kalıcı olarak bağlanır:','Google Play Android uygulamasında alın. Ödüller burada da eşitlenir.','Almak veya geri yüklemek için giriş yapın.','Ödül dağıtımı henüz etkin değil.','Kontrol ediliyor…','Doğrulanamadı. Daha sonra deneyin.','Hediye yok. Ön kayıt Google Play hesabını kontrol edin.','Başka bir oyun hesabına bağlı.','Google Play işliyor. Daha sonra deneyin.','Ödül kaydedildi. Play onayı bekleniyor; sonra yeniden geri yükleyin.'],
 pl:['Kolekcja założycieli','Korona założycieli','Obsydian i złota intarsja','Kość słoniowa i onyks · Założyciele','Bonus za wcześniejszą rejestrację w Google Play: trzy wyglądy bez przewagi w grze.','Odbierz / przywróć bezpłatnie','Sprawdź ponownie','Zdobyto · wybierz w ustawieniach wyglądu','Podgląd','Na stałe przypisany do tego konta:','Odbierz w aplikacji Android z Google Play. Nagrody synchronizują się też tutaj.','Zaloguj się, aby odebrać lub przywrócić.','Przyznawanie nagród jeszcze nieaktywne.','Sprawdzanie…','Nie udało się zweryfikować. Spróbuj później.','Brak bonusu. Sprawdź konto Google Play wcześniejszej rejestracji.','Przypisano do innego konta.','Google Play przetwarza nagrodę. Spróbuj później.','Nagroda zapisana. Potwierdzenie Play oczekuje; przywróć później.'],
 hi:['संस्थापक संग्रह','संस्थापक मुकुट','ओब्सीडियन और सोने की जड़ाई','हाथीदाँत और गोमेद · संस्थापक','Google Play पूर्व-पंजीकरण बोनस: तीन सजावटें। खेल में अतिरिक्त लाभ नहीं।','मुफ़्त बोनस लें / बहाल करें','फिर जाँचें','प्राप्त · रूप-रंग सेटिंग में चुनें','पूर्वावलोकन','इस गेम खाते से स्थायी रूप से जुड़ेगा:','Google Play से इंस्टॉल किए Android ऐप में लें। पुरस्कार यहाँ भी सिंक होते हैं।','प्राप्त या बहाल करने के लिए लॉगिन करें।','पुरस्कार वितरण अभी चालू नहीं है।','जाँच जारी…','सत्यापन नहीं हो सका। बाद में प्रयास करें।','बोनस नहीं मिला। पूर्व-पंजीकरण का Google Play खाता जाँचें।','अन्य गेम खाते से जुड़ा है।','Google Play संसाधित कर रहा है। बाद में प्रयास करें।','पुरस्कार सुरक्षित है। Play पुष्टि लंबित है; बाद में फिर बहाल करें।'],
 pt:['Coleção dos fundadores','Coroa dos fundadores','Obsidiana e incrustações de ouro','Marfim e ônix · Fundadores','Bônus de pré-registro no Google Play: três visuais sem vantagem nas partidas.','Receber / restaurar grátis','Verificar novamente','Obtido · escolha em Aparência','Prévia','Vinculado permanentemente a esta conta:','Receba no Android instalado pelo Google Play. As recompensas também são sincronizadas aqui.','Entre para receber ou restaurar.','A entrega ainda não está ativada.','Verificando…','Não foi possível verificar. Tente mais tarde.','Bônus não encontrado. Confira a conta Google Play do pré-registro.','Já vinculado a outra conta.','Google Play está processando. Tente mais tarde.','Recompensa salva. Confirmação Play pendente; restaure mais tarde.'],
 ta:['நிறுவனர் தொகுப்பு','நிறுவனர் கிரீடம்','ஒப்சிடியன் மற்றும் தங்கப் பதிப்பு','தந்தம் மற்றும் ஓனிக்ஸ் · நிறுவனர்','Google Play முன்பதிவுப் பரிசு: மூன்று அலங்காரங்கள். ஆட்ட வலிமையை மாற்றாது.','இலவசப் பரிசைப் பெற / மீட்டெடுக்க','மீண்டும் சரிபார்','பெற்றுவிட்டீர்கள் · தோற்ற அமைப்பில் தேர்ந்தெடுக்கவும்','முன்னோட்டம்','இந்தக் கணக்குடன் நிரந்தரமாக இணைக்கப்படும்:','Google Play மூலம் நிறுவிய Android செயலியில் பெறவும். பரிசுகள் இங்கும் ஒத்திசைக்கப்படும்.','பெற அல்லது மீட்டெடுக்க உள்நுழையவும்.','பரிசு வழங்கல் இன்னும் இயக்கப்படவில்லை.','சரிபார்க்கிறது…','சரிபார்க்க முடியவில்லை. பிறகு முயலவும்.','பரிசு இல்லை. முன்பதிவு Google Play கணக்கைச் சரிபார்க்கவும்.','வேறு கணக்குடன் இணைக்கப்பட்டுள்ளது.','Google Play செயலாக்குகிறது. பிறகு முயலவும்.','பரிசு சேமிக்கப்பட்டது. Play உறுதி நிலுவையில் உள்ளது; பிறகு மீட்டெடுக்கவும்.'],
};
export const foundersText=(lang:Language,key:typeof keys[number])=>copy[lang][keys.indexOf(key)];
export const foundersRewardName=(lang:Language,id:string)=>id===FOUNDERS_FRAME_ID?foundersText(lang,'frame'):id===FOUNDERS_BOARD_ID?foundersText(lang,'board'):id===FOUNDERS_PIECE_ID?foundersText(lang,'piece'):undefined;
