import type { Language } from './dict';
const keys = ['change','photo','earned','choose','save','cancel','preview','rule','locked','portrait','failed','auth','invalid','large','saving','localProgress'] as const;
type Copy = readonly [string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string];
const copy: Record<Language, Copy> = {
    ja:['アイコン変更','写真を使う','獲得アイコンを使う','写真を選択','このアイコンに変更','キャンセル','プレビュー','PNG・JPEG・WebP、2MB以下。中央を正方形に切り抜きます。','ステージ {n} で解放','サーキット・ポートレート {n}','変更できませんでした。再試行してください。','ログインを確認してから再試行してください。','PNG・JPEG・WebPの写真を選択してください。','写真は2MB以下にしてください。','保存中…','獲得状況はこの端末のサーキット進行から表示しています。'],
    en:['Change icon','Use a photo','Use earned icons','Choose photo','Apply this icon','Cancel','Preview','PNG, JPEG or WebP, up to 2MB. Photos are cropped to a centered square.','Unlock at stage {n}','Circuit portrait {n}','Could not update your icon. Please retry.','Verify your login, then retry.','Choose a PNG, JPEG or WebP photo.','Choose a photo no larger than 2MB.','Saving…','Unlocks reflect Circuit progress stored on this device.'],
    zh:['更换头像','使用照片','使用已获得头像','选择照片','应用头像','取消','预览','PNG、JPEG或WebP，不超过2MB，居中裁剪为正方形。','第{n}关解锁','巡回赛头像 {n}','更新失败，请重试。','请确认登录后重试。','请选择PNG、JPEG或WebP照片。','照片不能超过2MB。','保存中…','解锁状态依据此设备保存的巡回赛进度。'],
    ru:['Изменить аватар','Использовать фото','Наградные аватары','Выбрать фото','Применить аватар','Отмена','Предпросмотр','PNG, JPEG или WebP до 2 МБ. Обрезка по центру до квадрата.','Открывается на этапе {n}','Портрет Circuit {n}','Не удалось изменить аватар. Повторите.','Подтвердите вход и повторите.','Выберите фото PNG, JPEG или WebP.','Фото должно быть не более 2 МБ.','Сохранение…','Награды основаны на прогрессе Circuit на этом устройстве.'],
    fr:['Changer d’icône','Utiliser une photo','Icônes obtenues','Choisir une photo','Appliquer cette icône','Annuler','Aperçu','PNG, JPEG ou WebP, 2 Mo maximum. Recadrage carré centré.','Débloqué à l’étape {n}','Portrait Circuit {n}','Échec de la modification. Réessayez.','Vérifiez votre connexion, puis réessayez.','Choisissez une photo PNG, JPEG ou WebP.','La photo doit faire moins de 2 Mo.','Enregistrement…','Les récompenses suivent la progression Circuit de cet appareil.'],
    de:['Symbol ändern','Foto verwenden','Erhaltene Symbole','Foto auswählen','Symbol übernehmen','Abbrechen','Vorschau','PNG, JPEG oder WebP bis 2 MB. Mittiger quadratischer Zuschnitt.','Ab Stufe {n}','Circuit-Porträt {n}','Änderung fehlgeschlagen. Erneut versuchen.','Anmeldung bestätigen und erneut versuchen.','PNG-, JPEG- oder WebP-Foto wählen.','Das Foto darf höchstens 2 MB groß sein.','Wird gespeichert…','Freischaltungen basieren auf dem Circuit-Fortschritt dieses Geräts.'],
    es:['Cambiar icono','Usar una foto','Iconos obtenidos','Elegir foto','Aplicar este icono','Cancelar','Vista previa','PNG, JPEG o WebP, máximo 2 MB. Recorte cuadrado centrado.','Se desbloquea en la etapa {n}','Retrato del Circuito {n}','No se pudo cambiar. Inténtalo de nuevo.','Verifica tu sesión y vuelve a intentarlo.','Elige una foto PNG, JPEG o WebP.','La foto no debe superar 2 MB.','Guardando…','Los desbloqueos reflejan el progreso del Circuito en este dispositivo.'],
    tr:['Simgeyi değiştir','Fotoğraf kullan','Kazanılan simgeler','Fotoğraf seç','Bu simgeyi uygula','İptal','Önizleme','PNG, JPEG veya WebP, en çok 2 MB. Ortalanmış kare kırpma.','{n}. aşamada açılır','Circuit portresi {n}','Simge güncellenemedi. Tekrar deneyin.','Girişinizi doğrulayıp tekrar deneyin.','PNG, JPEG veya WebP fotoğraf seçin.','En fazla 2 MB fotoğraf seçin.','Kaydediliyor…','Kazanımlar bu cihazdaki Circuit ilerlemesine dayanır.'],
    pl:['Zmień ikonę','Użyj zdjęcia','Zdobyte ikony','Wybierz zdjęcie','Zastosuj ikonę','Anuluj','Podgląd','PNG, JPEG lub WebP do 2 MB. Centralne przycięcie do kwadratu.','Od etapu {n}','Portret Circuit {n}','Nie udało się zmienić ikony. Ponów próbę.','Potwierdź logowanie i spróbuj ponownie.','Wybierz zdjęcie PNG, JPEG lub WebP.','Zdjęcie może mieć najwyżej 2 MB.','Zapisywanie…','Nagrody odpowiadają postępowi Circuit na tym urządzeniu.'],
    hi:['आइकन बदलें','फ़ोटो इस्तेमाल करें','अर्जित आइकन','फ़ोटो चुनें','यह आइकन लगाएँ','रद्द करें','पूर्वावलोकन','PNG, JPEG या WebP, अधिकतम 2MB। बीच से वर्गाकार काटा जाएगा।','चरण {n} पर उपलब्ध','सर्किट पोर्ट्रेट {n}','आइकन नहीं बदला जा सका। पुनः प्रयास करें।','लॉगिन सत्यापित कर पुनः प्रयास करें।','PNG, JPEG या WebP फ़ोटो चुनें।','2MB से छोटी फ़ोटो चुनें।','सहेज रहे हैं…','अनलॉक इस डिवाइस की सर्किट प्रगति पर आधारित हैं।'],
    pt:['Alterar ícone','Usar uma foto','Ícones conquistados','Escolher foto','Aplicar este ícone','Cancelar','Prévia','PNG, JPEG ou WebP, até 2 MB. Corte quadrado centralizado.','Desbloqueia na fase {n}','Retrato do Circuito {n}','Não foi possível alterar. Tente novamente.','Confirme seu login e tente novamente.','Escolha uma foto PNG, JPEG ou WebP.','Escolha uma foto de até 2 MB.','Salvando…','Os desbloqueios seguem o progresso do Circuito neste dispositivo.'],
    ta:['ஐகானை மாற்று','புகைப்படம் பயன்படுத்து','பெற்ற ஐகான்கள்','புகைப்படத்தைத் தேர்ந்தெடு','இந்த ஐகானைப் பயன்படுத்து','ரத்து','முன்னோட்டம்','PNG, JPEG அல்லது WebP, அதிகபட்சம் 2MB. மையத்தில் சதுரமாக வெட்டப்படும்.','நிலை {n} இல் திறக்கும்','சர்க்யூட் உருவப்படம் {n}','மாற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.','உள்நுழைவை உறுதிசெய்து மீண்டும் முயற்சிக்கவும்.','PNG, JPEG அல்லது WebP படத்தைத் தேர்ந்தெடுக்கவும்.','2MB-க்கு மிகாத படத்தைத் தேர்ந்தெடுக்கவும்.','சேமிக்கிறது…','இந்தச் சாதனத்தின் சர்க்யூட் முன்னேற்றத்தின் அடிப்படையில் திறக்கப்படும்.'],
};
export type IconEditorTextKey = typeof keys[number];
export const iconEditorText = (lang: string, key: IconEditorTextKey, n?: number) => (copy[lang as Language] ?? copy.en)[keys.indexOf(key)].replace('{n}', String(n ?? ''));
