import { matchText } from './matchText';
type HintText = {
    free: string; ticket: string; thinking: string; recover: string; saved: string; historical: string;
    missing: string; auth: string; funds: string; storage: string; stale: string; terms: string; unavailable: string; sync: string;
};
const text: Record<string, HintText> = {
    ja: {free:'無料でQUBEに聞く',ticket:'ヒント券を使用（1枚）',thinking:'QUBEが考え中…',recover:'ヒントを再取得（追加消費なし）',saved:'保存済みヒント',historical:'以前の局面のヒントです。現在の盤面には適用されません。',missing:'保存済みヒントはありません。',auth:'ヒント券を使うには登録アカウントでログインしてください。',funds:'ヒント券がありません。',storage:'再取得に必要な情報を保存できません。ブラウザーの保存設定を確認してください。',stale:'局面が変わりました。最新の局面でヒントを選んでください。',terms:'最新の利用規約への同意が必要です。ホームで確認してください。',unavailable:'ヒントを取得できませんでした。送信済みの場合は追加消費なしの再取得をお試しください。',sync:'対局データを同期してください。'},
    en: {free:'Ask QUBE for free',ticket:'Use 1 hint ticket',thinking:'QUBE is thinking…',recover:'Retrieve hint (no extra ticket)',saved:'Saved hint',historical:'This hint belongs to an earlier position and does not apply to the current board.',missing:'No saved hint is available.',auth:'Sign in to a registered account to use hint tickets.',funds:'No hint tickets remain.',storage:'Recovery details could not be saved. Check your browser storage settings.',stale:'The position changed. Request a hint for the current position.',terms:'Accept the current terms from the home screen first.',unavailable:'Hint unavailable. If already sent, retrieve it without an extra ticket.',sync:'Reconnect the game data.'},
    zh: {free:'免费向QUBE求助',ticket:'使用1张提示券',thinking:'QUBE正在思考…',recover:'重新获取提示（不额外扣券）',saved:'已保存的提示',historical:'此提示对应先前的局面，不适用于当前棋盘。',missing:'没有已保存的提示。',auth:'请登录注册账户以使用提示券。',funds:'提示券不足。',storage:'无法保存恢复信息。请检查浏览器的存储设置。',stale:'局面已变化。请为当前局面请求提示。',terms:'请先在主页同意最新条款。',unavailable:'无法获取提示。如已发送，请重新获取，无需额外提示券。',sync:'请重新同步对局数据。'},
    ru: {free:'Спросить QUBE бесплатно',ticket:'Использовать 1 билет подсказки',thinking:'QUBE думает…',recover:'Вернуть подсказку (без нового билета)',saved:'Сохранённая подсказка',historical:'Подсказка относится к прежней позиции и не применяется к текущей доске.',missing:'Сохранённой подсказки нет.',auth:'Войдите в зарегистрированную учётную запись для использования билетов.',funds:'Билетов подсказки нет.',storage:'Не удалось сохранить данные восстановления. Проверьте хранилище браузера.',stale:'Позиция изменилась. Запросите подсказку для текущей позиции.',terms:'Сначала примите актуальные условия на главном экране.',unavailable:'Подсказка недоступна. Если запрос отправлен, восстановите её без нового билета.',sync:'Синхронизируйте данные партии.'},
    fr: {free:'Demander gratuitement à QUBE',ticket:'Utiliser 1 ticket d’indice',thinking:'QUBE réfléchit…',recover:'Récupérer l’indice (sans ticket supplémentaire)',saved:'Indice enregistré',historical:'Cet indice correspond à une position précédente, pas au plateau actuel.',missing:'Aucun indice enregistré.',auth:'Connectez-vous à un compte enregistré pour utiliser des tickets.',funds:'Aucun ticket d’indice disponible.',storage:'Impossible de sauvegarder les données de récupération. Vérifiez le stockage du navigateur.',stale:'La position a changé. Demandez un indice pour la position actuelle.',terms:'Acceptez d’abord les conditions actuelles depuis l’accueil.',unavailable:'Indice indisponible. Si la demande a été envoyée, récupérez-le sans ticket supplémentaire.',sync:'Synchronisez les données de la partie.'},
    de: {free:'QUBE kostenlos fragen',ticket:'1 Hinweis-Ticket verwenden',thinking:'QUBE denkt nach…',recover:'Hinweis abrufen (ohne weiteres Ticket)',saved:'Gespeicherter Hinweis',historical:'Dieser Hinweis gehört zu einer früheren Stellung und gilt nicht für das aktuelle Brett.',missing:'Kein gespeicherter Hinweis vorhanden.',auth:'Melde dich mit einem registrierten Konto an, um Tickets zu verwenden.',funds:'Keine Hinweis-Tickets vorhanden.',storage:'Wiederherstellungsdaten konnten nicht gespeichert werden. Prüfe den Browserspeicher.',stale:'Die Stellung hat sich geändert. Fordere einen Hinweis für die aktuelle Stellung an.',terms:'Akzeptiere zuerst die aktuellen Bedingungen auf der Startseite.',unavailable:'Hinweis nicht verfügbar. Falls bereits gesendet, rufe ihn ohne weiteres Ticket ab.',sync:'Synchronisiere die Partiedaten.'},
    es: {free:'Consultar a QUBE gratis',ticket:'Usar 1 boleto de pista',thinking:'QUBE está pensando…',recover:'Recuperar pista (sin otro boleto)',saved:'Pista guardada',historical:'Esta pista corresponde a una posición anterior y no al tablero actual.',missing:'No hay ninguna pista guardada.',auth:'Inicia sesión en una cuenta registrada para usar boletos.',funds:'No quedan boletos de pista.',storage:'No se pudieron guardar los datos de recuperación. Revisa el almacenamiento del navegador.',stale:'La posición cambió. Pide una pista para la posición actual.',terms:'Acepta primero los términos actuales desde el inicio.',unavailable:'Pista no disponible. Si ya se envió, recupérala sin otro boleto.',sync:'Sincroniza los datos de la partida.'},
    tr: {free:'QUBE’a ücretsiz sor',ticket:'1 ipucu bileti kullan',thinking:'QUBE düşünüyor…',recover:'İpucunu geri getir (ek bilet yok)',saved:'Kaydedilmiş ipucu',historical:'Bu ipucu önceki bir konuma aittir; mevcut tahta için geçerli değildir.',missing:'Kaydedilmiş ipucu yok.',auth:'Bilet kullanmak için kayıtlı hesabına giriş yap.',funds:'İpucu bileti kalmadı.',storage:'Kurtarma bilgileri kaydedilemedi. Tarayıcı depolama ayarlarını kontrol et.',stale:'Konum değişti. Mevcut konum için ipucu iste.',terms:'Önce ana ekranda güncel şartları kabul et.',unavailable:'İpucu alınamadı. İstek gönderildiyse ek bilet kullanmadan geri getir.',sync:'Oyun verilerini eşitle.'},
    pl: {free:'Zapytaj QUBE bezpłatnie',ticket:'Użyj 1 biletu podpowiedzi',thinking:'QUBE myśli…',recover:'Odzyskaj podpowiedź (bez kolejnego biletu)',saved:'Zapisana podpowiedź',historical:'Ta podpowiedź dotyczy wcześniejszej pozycji, a nie obecnej planszy.',missing:'Brak zapisanej podpowiedzi.',auth:'Zaloguj się na zarejestrowane konto, aby używać biletów.',funds:'Brak biletów podpowiedzi.',storage:'Nie zapisano danych odzyskiwania. Sprawdź ustawienia pamięci przeglądarki.',stale:'Pozycja się zmieniła. Poproś o podpowiedź dla obecnej pozycji.',terms:'Najpierw zaakceptuj aktualny regulamin na ekranie głównym.',unavailable:'Podpowiedź niedostępna. Jeśli wysłano prośbę, odzyskaj ją bez kolejnego biletu.',sync:'Zsynchronizuj dane partii.'},
    hi: {free:'QUBE से मुफ़्त में पूछें',ticket:'1 संकेत टिकट इस्तेमाल करें',thinking:'QUBE सोच रहा है…',recover:'संकेत फिर पाएँ (अतिरिक्त टिकट नहीं)',saved:'सहेजा गया संकेत',historical:'यह संकेत पिछली स्थिति का है और मौजूदा बोर्ड पर लागू नहीं है।',missing:'कोई सहेजा गया संकेत नहीं है।',auth:'टिकट इस्तेमाल करने के लिए पंजीकृत खाते में लॉग इन करें।',funds:'संकेत टिकट नहीं बचे हैं।',storage:'पुनर्प्राप्ति जानकारी सहेजी नहीं जा सकी। ब्राउज़र की स्टोरेज सेटिंग जाँचें।',stale:'स्थिति बदल गई है। मौजूदा स्थिति के लिए संकेत माँगें।',terms:'पहले होम स्क्रीन पर मौजूदा शर्तें स्वीकार करें।',unavailable:'संकेत उपलब्ध नहीं है। अनुरोध भेजा गया हो तो बिना अतिरिक्त टिकट के फिर पाएँ।',sync:'खेल का डेटा फिर सिंक करें।'},
    pt: {free:'Perguntar ao QUBE de graça',ticket:'Usar 1 bilhete de dica',thinking:'QUBE está pensando…',recover:'Recuperar dica (sem outro bilhete)',saved:'Dica salva',historical:'Esta dica pertence a uma posição anterior e não se aplica ao tabuleiro atual.',missing:'Não há dica salva.',auth:'Entre em uma conta registrada para usar bilhetes.',funds:'Não há bilhetes de dica.',storage:'Não foi possível salvar os dados de recuperação. Confira o armazenamento do navegador.',stale:'A posição mudou. Peça uma dica para a posição atual.',terms:'Aceite primeiro os termos atuais na tela inicial.',unavailable:'Dica indisponível. Se o pedido já foi enviado, recupere-a sem outro bilhete.',sync:'Sincronize os dados da partida.'},
    ta: {free:'QUBE-இடம் இலவசமாகக் கேள்',ticket:'1 குறிப்புச் சீட்டைப் பயன்படுத்து',thinking:'QUBE யோசிக்கிறது…',recover:'குறிப்பை மீட்டெடு (கூடுதல் சீட்டு இல்லை)',saved:'சேமிக்கப்பட்ட குறிப்பு',historical:'இந்தக் குறிப்பு முந்தைய நிலைக்கானது; தற்போதைய பலகைக்குப் பொருந்தாது.',missing:'சேமிக்கப்பட்ட குறிப்பு இல்லை.',auth:'சீட்டுகளைப் பயன்படுத்தப் பதிவு செய்த கணக்கில் உள்நுழையவும்.',funds:'குறிப்புச் சீட்டுகள் இல்லை.',storage:'மீட்புத் தகவலைச் சேமிக்க முடியவில்லை. உலாவியின் சேமிப்பு அமைப்பைப் பார்க்கவும்.',stale:'நிலை மாறிவிட்டது. தற்போதைய நிலைக்குக் குறிப்பு கேட்கவும்.',terms:'முதலில் முகப்பில் தற்போதைய விதிமுறைகளை ஏற்கவும்.',unavailable:'குறிப்பு கிடைக்கவில்லை. கோரிக்கை அனுப்பப்பட்டிருந்தால் கூடுதல் சீட்டின்றி மீட்டெடுக்கவும்.',sync:'ஆட்டத் தரவை ஒத்திசைக்கவும்.'},
};
export const moveHintText = (lang: string): HintText => ({ ...(text[lang] ?? text.en), thinking: matchText(lang,'QUBEが考え中…','QUBE is thinking…') });
export function hintErrorText(lang: string, error: unknown): string {
    const code = error && typeof error === 'object' && 'code' in error ? error.code : null, t = moveHintText(lang);
    if (code === 'AUTH_REQUIRED' || code === 'ACCOUNT_UNAVAILABLE') return t.auth;
    if (code === 'INSUFFICIENT_FUNDS') return t.funds;
    if (code === 'REQUEST_STORAGE_UNAVAILABLE') return t.storage;
    if (code === 'TERMS_REQUIRED') return t.terms;
    if (code === 'NO_SAVED_HINT') return t.missing;
    if (['STALE_REVISION', 'SESSION_FINISHED', 'HINT_CONTEXT_EXPIRED'].includes(String(code))) return t.stale;
    return t.unavailable;
}
