import type { Language } from './dict';

type Copy = { refunds: string; freeRefunds: string; paidRefunds: string; refundPolicy: string; paidPolicy: string;
    admitting: string; recovering: string; unavailable: string; checking: string; settled: string };
const copy: Record<Language, Copy> = {
    en: { refunds:'Available ranked refund credits', freeRefunds:'Returned free tickets', paidRefunds:'Returned member tickets', refundPolicy:'These credits restore tickets used by cancelled matches. They are separate from ordinary tickets, can be used for ranked matches, and are not limited to 20.', paidPolicy:'Member credits show only the amount eligible at the last check. Expired, revoked, refunded or suspended credits are excluded. Eligibility is checked again when a match starts.', admitting:'Preparing the ranked match…', recovering:'Recovering the match and checking its result or ticket return…', unavailable:'Recovery is temporarily unavailable. Retrying the match status check…', checking:'Checking the match status…', settled:'The saved match result was recovered.' },
    ja: { refunds:'利用可能なランク戦返還クレジット', freeRefunds:'無料券の返還分', paidRefunds:'会員券の返還分', refundPolicy:'中止された対局で使った券の返還分です。通常の券と別枠でランク戦に使え、20枚の上限はありません。', paidPolicy:'会員券の返還分は確認時点で有効な数だけを表示します。期限切れ・失効・返金・決済取消・利用停止分は含みません。対局開始時にも利用資格を確認します。', admitting:'ランク戦を準備しています…', recovering:'対局を復旧し、結果または券の返還を確認しています…', unavailable:'一時的に復旧を確認できません。対局状態を再確認しています…', checking:'対局状態を確認しています…', settled:'保存済みの対局結果を復元しました。' },
    zh: { refunds:'可用排位赛返还额度', freeRefunds:'返还的免费券', paidRefunds:'返还的会员券', refundPolicy:'这是因对局取消而返还的已用券。与普通券分开，可用于排位赛，不受20张上限限制。', paidPolicy:'会员返还额度仅显示上次检查时可用的数量，不含过期、失效、退款、撤销付款或暂停使用的额度。开局时会再次确认使用资格。', admitting:'正在准备排位赛…', recovering:'正在恢复对局并确认结果或返还券…', unavailable:'暂时无法确认恢复状态，正在重试…', checking:'正在检查对局状态…', settled:'已恢复保存的对局结果。' },
    ru: { refunds:'Доступные возвраты рейтинговых билетов', freeRefunds:'Возвращённые бесплатные билеты', paidRefunds:'Возвращённые билеты подписки', refundPolicy:'Это возвраты билетов за отменённые матчи. Они учитываются отдельно, используются в рейтинговых матчах и не ограничены 20 билетами.', paidPolicy:'Показаны только возвраты подписки, доступные при последней проверке. Истёкшие, отозванные, возвращённые по платежу или приостановленные исключены. При старте матча доступность проверяется снова.', admitting:'Подготовка рейтингового матча…', recovering:'Восстановление матча и проверка результата или возврата билета…', unavailable:'Восстановление временно недоступно. Повторная проверка состояния…', checking:'Проверка состояния матча…', settled:'Сохранённый результат матча восстановлен.' },
    fr: { refunds:'Crédits de restitution classés disponibles', freeRefunds:'Tickets gratuits restitués', paidRefunds:'Tickets d’abonnement restitués', refundPolicy:'Ces crédits restituent les tickets utilisés dans des parties annulées. Séparés des tickets ordinaires, ils servent aux parties classées et ne sont pas limités à 20.', paidPolicy:'Seuls les crédits d’abonnement éligibles lors de la dernière vérification sont affichés. Les crédits expirés, révoqués, remboursés ou suspendus sont exclus. L’éligibilité est revérifiée au début de la partie.', admitting:'Préparation de la partie classée…', recovering:'Récupération de la partie et vérification du résultat ou de la restitution…', unavailable:'Récupération temporairement indisponible. Nouvelle vérification en cours…', checking:'Vérification de l’état de la partie…', settled:'Le résultat sauvegardé de la partie a été récupéré.' },
    de: { refunds:'Verfügbare Ranglisten-Rückgabeguthaben', freeRefunds:'Zurückgegebene kostenlose Tickets', paidRefunds:'Zurückgegebene Mitgliedschafts-Tickets', refundPolicy:'Diese Guthaben ersetzen Tickets aus abgebrochenen Spielen. Sie sind von normalen Tickets getrennt, für Ranglistenspiele nutzbar und nicht auf 20 begrenzt.', paidPolicy:'Angezeigt werden nur bei der letzten Prüfung nutzbare Mitgliedschaftsguthaben. Abgelaufene, widerrufene, erstattete oder gesperrte Guthaben sind ausgeschlossen. Beim Spielstart wird die Berechtigung erneut geprüft.', admitting:'Ranglistenspiel wird vorbereitet…', recovering:'Spiel wird wiederhergestellt; Ergebnis oder Ticketrückgabe wird geprüft…', unavailable:'Wiederherstellung vorübergehend nicht verfügbar. Status wird erneut geprüft…', checking:'Spielstatus wird geprüft…', settled:'Das gespeicherte Spielergebnis wurde wiederhergestellt.' },
    es: { refunds:'Créditos devueltos disponibles para clasificatorias', freeRefunds:'Boletos gratuitos devueltos', paidRefunds:'Boletos de membresía devueltos', refundPolicy:'Estos créditos devuelven boletos usados en partidas canceladas. Están separados de los boletos normales, sirven para clasificatorias y no tienen el límite de 20.', paidPolicy:'Solo se muestra el crédito de membresía válido en la última consulta. Se excluyen créditos vencidos, revocados, reembolsados o suspendidos. La validez se revisa otra vez al comenzar la partida.', admitting:'Preparando la partida clasificatoria…', recovering:'Recuperando la partida y comprobando el resultado o la devolución…', unavailable:'La recuperación no está disponible temporalmente. Reintentando la consulta…', checking:'Comprobando el estado de la partida…', settled:'Se recuperó el resultado guardado de la partida.' },
    tr: { refunds:'Kullanılabilir dereceli maç iade hakları', freeRefunds:'İade edilen ücretsiz biletler', paidRefunds:'İade edilen üyelik biletleri', refundPolicy:'Bu haklar iptal edilen maçlarda kullanılan biletleri geri verir. Normal biletlerden ayrıdır, dereceli maçlarda kullanılır ve 20 sınırı yoktur.', paidPolicy:'Yalnızca son kontrolde uygun olan üyelik iade hakları gösterilir. Süresi dolan, geri alınan, ödemesi iade edilen veya askıya alınan haklar sayılmaz. Maç başlarken uygunluk yeniden kontrol edilir.', admitting:'Dereceli maç hazırlanıyor…', recovering:'Maç kurtarılıyor; sonuç veya bilet iadesi kontrol ediliyor…', unavailable:'Kurtarma geçici olarak kullanılamıyor. Durum yeniden kontrol ediliyor…', checking:'Maç durumu kontrol ediliyor…', settled:'Kaydedilmiş maç sonucu kurtarıldı.' },
    pl: { refunds:'Dostępne zwroty biletów rankingowych', freeRefunds:'Zwrócone darmowe bilety', paidRefunds:'Zwrócone bilety członkowskie', refundPolicy:'To zwroty biletów użytych w anulowanych meczach. Są oddzielone od zwykłych biletów, służą do gier rankingowych i nie mają limitu 20.', paidPolicy:'Widoczne są tylko zwroty członkowskie dostępne podczas ostatniej kontroli. Wygasłe, cofnięte, objęte zwrotem płatności lub zawieszone są pomijane. Uprawnienia są ponownie sprawdzane przy starcie meczu.', admitting:'Przygotowywanie meczu rankingowego…', recovering:'Odzyskiwanie meczu i sprawdzanie wyniku lub zwrotu biletu…', unavailable:'Odzyskiwanie jest chwilowo niedostępne. Ponowne sprawdzanie stanu…', checking:'Sprawdzanie stanu meczu…', settled:'Odzyskano zapisany wynik meczu.' },
    hi: { refunds:'उपलब्ध रैंक्ड वापसी क्रेडिट', freeRefunds:'वापस मिले मुफ़्त टिकट', paidRefunds:'वापस मिले सदस्यता टिकट', refundPolicy:'ये रद्द मैचों में इस्तेमाल हुए टिकटों की वापसी हैं। सामान्य टिकटों से अलग हैं, रैंक्ड मैचों में इस्तेमाल होते हैं और इन पर 20 की सीमा नहीं है।', paidPolicy:'पिछली जाँच के समय मान्य सदस्यता क्रेडिट ही दिखते हैं। समाप्त, निरस्त, धनवापसी वाले या निलंबित क्रेडिट शामिल नहीं हैं। मैच शुरू होते समय पात्रता फिर जाँची जाती है।', admitting:'रैंक्ड मैच तैयार हो रहा है…', recovering:'मैच बहाल करके परिणाम या टिकट वापसी जाँची जा रही है…', unavailable:'बहाली अभी उपलब्ध नहीं है। मैच की स्थिति फिर जाँची जा रही है…', checking:'मैच की स्थिति जाँची जा रही है…', settled:'सहेजा गया मैच परिणाम बहाल हो गया।' },
    pt: { refunds:'Créditos devolvidos disponíveis para ranqueadas', freeRefunds:'Bilhetes gratuitos devolvidos', paidRefunds:'Bilhetes da assinatura devolvidos', refundPolicy:'Estes créditos devolvem bilhetes usados em partidas canceladas. São separados dos bilhetes comuns, servem para ranqueadas e não têm limite de 20.', paidPolicy:'São exibidos apenas os créditos da assinatura elegíveis na última consulta. Créditos expirados, revogados, reembolsados ou suspensos são excluídos. A elegibilidade é verificada novamente ao iniciar a partida.', admitting:'Preparando a partida ranqueada…', recovering:'Recuperando a partida e verificando o resultado ou a devolução…', unavailable:'Recuperação temporariamente indisponível. Consultando o estado novamente…', checking:'Verificando o estado da partida…', settled:'O resultado salvo da partida foi recuperado.' },
    ta: { refunds:'கிடைக்கும் தரவரிசை திருப்புக் கிரெடிட்கள்', freeRefunds:'திரும்பப் பெற்ற இலவசச் சீட்டுகள்', paidRefunds:'திரும்பப் பெற்ற உறுப்பினர் சீட்டுகள்', refundPolicy:'ரத்து செய்யப்பட்ட போட்டிகளில் பயன்படுத்திய சீட்டுகளின் திருப்பங்கள் இவை. வழக்கமான சீட்டுகளிலிருந்து தனியாக உள்ளன; தரவரிசைப் போட்டிகளில் பயன்படுத்தலாம்; 20 என்ற வரம்பு இல்லை.', paidPolicy:'கடைசிச் சரிபார்ப்பில் தகுதியுள்ள உறுப்பினர் கிரெடிட்கள் மட்டுமே காட்டப்படும். காலாவதியான, நீக்கப்பட்ட, பணம் திருப்பப்பட்ட அல்லது இடைநிறுத்தப்பட்டவை சேர்க்கப்படாது. போட்டி தொடங்கும்போது தகுதி மீண்டும் சரிபார்க்கப்படும்.', admitting:'தரவரிசைப் போட்டி தயாராகிறது…', recovering:'போட்டியை மீட்டு முடிவு அல்லது சீட்டு திருப்பத்தைச் சரிபார்க்கிறது…', unavailable:'மீட்பு தற்காலிகமாகக் கிடைக்கவில்லை. நிலையை மீண்டும் சரிபார்க்கிறது…', checking:'போட்டி நிலையைச் சரிபார்க்கிறது…', settled:'சேமித்த போட்டி முடிவு மீட்கப்பட்டது.' },
};
export const rankedRecoveryText = (lang: Language): Copy => copy[lang];
