import type { Language } from './dict';

type Copy = Readonly<{
    title: string; description: string; rules: string; balance: string;
    today: string; automatic: string; optional: string; review: string;
    monthly: string; limit: string; full: string;
}>;
const copy: Record<Language, Copy> = {
    ja: { title:'チケット・報酬', description:'残高とログイン特典をまとめて確認', rules:'受取・使い方のルール', balance:'使える無料券', today:'今日のログイン報酬', automatic:'ログイン時に自動で受け取ります。規約の確認が必要な場合は下に表示します。', optional:'もっと遊びたい方へ · 加入は任意', review:'特典・購入条件を確認', monthly:'月額総額 · USD', limit:'保有上限', full:'上限に達しています。空きができた分だけ受け取れます。' },
    en: { title:'Tickets & rewards', description:'Your balances and login rewards in one place', rules:'How to earn and use tickets', balance:'Free tickets available', today:'Today’s login reward', automatic:'Rewards are collected automatically at login. Any required terms review appears below.', optional:'For more play · Membership is optional', review:'Review benefits & purchase terms', monthly:'Monthly total · USD', limit:'Balance limit', full:'At the limit. Only the space available can be credited.' },
    zh: { title:'券与奖励', description:'在此查看余额与登录奖励', rules:'领取与使用规则', balance:'可用免费券', today:'今日登录奖励', automatic:'登录时自动领取。如需确认条款，将在下方显示。', optional:'想多玩一些 · 会员为可选项', review:'查看权益与购买条件', monthly:'每月总价 · USD', limit:'持有上限', full:'已达上限，仅发放剩余容量允许的数量。' },
    ru: { title:'Билеты и награды', description:'Баланс и награды за вход в одном месте', rules:'Получение и использование билетов', balance:'Доступные бесплатные билеты', today:'Награда за вход сегодня', automatic:'Награды начисляются при входе. Если нужно принять условия, они появятся ниже.', optional:'Для дополнительных игр · Подписка необязательна', review:'Преимущества и условия покупки', monthly:'Итого в месяц · USD', limit:'Лимит хранения', full:'Достигнут лимит. Начисляется только доступное место.' },
    fr: { title:'Tickets et récompenses', description:'Vos soldes et récompenses de connexion', rules:'Obtenir et utiliser les tickets', balance:'Tickets gratuits disponibles', today:'Récompense de connexion du jour', automatic:'Les récompenses sont reçues à la connexion. Les conditions à accepter, le cas échéant, apparaissent ci-dessous.', optional:'Pour jouer davantage · Abonnement facultatif', review:'Avantages et conditions d’achat', monthly:'Total mensuel · USD', limit:'Plafond du solde', full:'Plafond atteint. Seule la place disponible peut être créditée.' },
    de: { title:'Tickets und Belohnungen', description:'Guthaben und Login-Belohnungen im Überblick', rules:'Tickets erhalten und verwenden', balance:'Verfügbare kostenlose Tickets', today:'Heutige Login-Belohnung', automatic:'Belohnungen werden beim Anmelden gutgeschrieben. Falls eine Zustimmung nötig ist, erscheint sie unten.', optional:'Für mehr Spiele · Mitgliedschaft ist optional', review:'Vorteile und Kaufbedingungen ansehen', monthly:'Monatlicher Gesamtpreis · USD', limit:'Guthabenlimit', full:'Limit erreicht. Es wird nur der verfügbare Platz aufgefüllt.' },
    es: { title:'Boletos y recompensas', description:'Tus saldos y premios de inicio de sesión', rules:'Cómo obtener y usar boletos', balance:'Boletos gratuitos disponibles', today:'Recompensa de inicio de sesión de hoy', automatic:'Se reciben automáticamente al iniciar sesión. Si debes aceptar las condiciones, aparecerán abajo.', optional:'Para jugar más · Membresía opcional', review:'Ver beneficios y condiciones de compra', monthly:'Total mensual · USD', limit:'Límite de saldo', full:'Límite alcanzado. Solo se acredita el espacio disponible.' },
    tr: { title:'Biletler ve ödüller', description:'Bakiyeler ve giriş ödülleri bir arada', rules:'Bilet kazanma ve kullanma', balance:'Kullanılabilir ücretsiz biletler', today:'Bugünün giriş ödülü', automatic:'Ödüller girişte otomatik alınır. Gerekli koşul onayı aşağıda gösterilir.', optional:'Daha fazla oyun için · Üyelik isteğe bağlıdır', review:'Avantajları ve satın alma koşullarını incele', monthly:'Aylık toplam · USD', limit:'Bakiye sınırı', full:'Sınıra ulaşıldı. Yalnızca boş alan kadar eklenir.' },
    pl: { title:'Bilety i nagrody', description:'Salda i nagrody za logowanie w jednym miejscu', rules:'Jak zdobywać i używać biletów', balance:'Dostępne darmowe bilety', today:'Dzisiejsza nagroda za logowanie', automatic:'Nagrody są przyznawane przy logowaniu. Wymagana akceptacja warunków pojawi się poniżej.', optional:'Więcej gry · Członkostwo jest opcjonalne', review:'Korzyści i warunki zakupu', monthly:'Suma miesięczna · USD', limit:'Limit salda', full:'Osiągnięto limit. Przyznawane jest tylko dostępne miejsce.' },
    hi: { title:'टिकट और इनाम', description:'शेष टिकट और लॉगिन इनाम एक जगह', rules:'टिकट पाने और इस्तेमाल करने के नियम', balance:'उपलब्ध मुफ़्त टिकट', today:'आज का लॉगिन इनाम', automatic:'लॉगिन पर इनाम अपने-आप मिलते हैं। शर्तों की स्वीकृति ज़रूरी हो तो नीचे दिखाई जाएगी।', optional:'और खेलने के लिए · सदस्यता वैकल्पिक है', review:'लाभ और खरीद की शर्तें देखें', monthly:'मासिक कुल · USD', limit:'रखने की सीमा', full:'सीमा पूरी है। केवल खाली जगह के अनुसार टिकट मिलेंगे।' },
    pt: { title:'Bilhetes e recompensas', description:'Saldos e recompensas de login num só lugar', rules:'Como obter e usar bilhetes', balance:'Bilhetes gratuitos disponíveis', today:'Recompensa de login de hoje', automatic:'As recompensas são recebidas ao entrar. Se for necessário aceitar os termos, eles aparecerão abaixo.', optional:'Para jogar mais · Assinatura opcional', review:'Ver benefícios e condições de compra', monthly:'Total mensal · USD', limit:'Limite de saldo', full:'Limite atingido. Só é creditado o espaço disponível.' },
    ta: { title:'சீட்டுகளும் வெகுமதிகளும்', description:'இருப்பும் உள்நுழைவு வெகுமதிகளும் ஒரே இடத்தில்', rules:'சீட்டுகளைப் பெறவும் பயன்படுத்தவும் விதிகள்', balance:'கிடைக்கும் இலவசச் சீட்டுகள்', today:'இன்றைய உள்நுழைவு வெகுமதி', automatic:'உள்நுழையும்போது வெகுமதிகள் தானாகப் பெறப்படும். விதிமுறை ஒப்புதல் தேவைப்பட்டால் கீழே தோன்றும்.', optional:'மேலும் விளையாட · உறுப்பினர் சேர்க்கை விருப்பமானது', review:'பலன்களையும் வாங்கும் விதிகளையும் பார்க்க', monthly:'மாத மொத்தம் · USD', limit:'இருப்பு வரம்பு', full:'வரம்பு எட்டப்பட்டது. மீதமுள்ள இடத்திற்கே சீட்டுகள் வழங்கப்படும்.' },
};
export const rewardsHubText = (lang: Language): Copy => copy[lang];
