import type {Language} from './dict';
export const securityPrivacy:Record<Language,string>={
    ja:'不正対策用の監査ログには操作種別・成否・サーバー日時・対象アカウントのみを記録します。保存期間は30日で、期限後は毎時の処理で削除します。パスワード・トークン・メール本文・生のIPアドレスはこのログに保存しません。本人がアカウントを削除した場合、紐づくログも削除します。休眠アカウントの自動削除は行いません。',
    en:'Security audit logs contain only action type, outcome, server time and the affected account. They are retained for 30 days and expired entries are removed hourly. These logs do not store passwords, tokens, email content or raw IP addresses. Linked logs are erased with account deletion. Inactive accounts are not automatically deleted.',
    zh:'安全审计日志仅记录操作类型、结果、服务器时间和相关账户，保留30天，每小时清理过期记录。不记录密码、令牌、邮件内容或原始IP地址。删除账户时一并删除关联日志，不自动删除长期未使用的账户。',
    ru:'Журнал безопасности содержит только действие, результат, время сервера и затронутый аккаунт. Срок хранения — 30 дней; просроченные записи удаляются ежечасно. Пароли, токены, письма и исходные IP не сохраняются в этом журнале. При удалении аккаунта удаляются связанные записи. Неактивные аккаунты автоматически не удаляются.',
    fr:'Le journal de sécurité contient uniquement action, résultat, heure serveur et compte concerné. Conservation : 30 jours, puis suppression horaire des entrées expirées. Aucun mot de passe, jeton, contenu d’e-mail ou IP brute n’y est enregistré. Les entrées liées sont effacées avec le compte. Les comptes inactifs ne sont pas supprimés automatiquement.',
    de:'Sicherheitsprotokolle enthalten nur Aktion, Ergebnis, Serverzeit und betroffenes Konto. Aufbewahrung: 30 Tage; abgelaufene Einträge werden stündlich gelöscht. Keine Passwörter, Token, E-Mail-Inhalte oder rohen IP-Adressen in diesen Protokollen. Verknüpfte Einträge werden bei Kontolöschung entfernt. Inaktive Konten werden nicht automatisch gelöscht.',
    es:'El registro de seguridad guarda solo acción, resultado, hora del servidor y cuenta afectada durante 30 días; las entradas vencidas se eliminan cada hora. No guarda contraseñas, tokens, contenido de correos ni IP sin procesar. Al borrar la cuenta se borran sus registros. Las cuentas inactivas no se eliminan automáticamente.',
    tr:'Güvenlik kayıtlarında yalnız işlem türü, sonuç, sunucu saati ve ilgili hesap bulunur. Kayıtlar 30 gün tutulur; süresi dolanlar saatlik silinir. Parola, belirteç, e-posta içeriği veya ham IP kaydedilmez. Hesap silinince bağlı kayıtlar da silinir. Etkin olmayan hesaplar otomatik silinmez.',
    pl:'Dziennik bezpieczeństwa zawiera tylko rodzaj działania, wynik, czas serwera i konto. Okres przechowywania to 30 dni; wygasłe wpisy są usuwane co godzinę. Nie zapisuje haseł, tokenów, treści e-maili ani surowych adresów IP. Powiązane wpisy są usuwane z kontem. Nieaktywne konta nie są usuwane automatycznie.',
    hi:'सुरक्षा लॉग में केवल कार्रवाई, परिणाम, सर्वर समय और संबंधित खाता रखा जाता है। अवधि 30 दिन है; पुराने रिकॉर्ड हर घंटे हटते हैं। इसमें पासवर्ड, टोकन, ईमेल सामग्री या मूल IP पते नहीं रखे जाते। खाता हटाने पर संबंधित लॉग भी हटते हैं। निष्क्रिय खाते अपने आप नहीं हटते।',
    pt:'O registro de segurança guarda apenas ação, resultado, hora do servidor e conta afetada por 30 dias; entradas expiradas são removidas a cada hora. Não guarda senhas, tokens, conteúdo de e-mails ou IPs brutos. Registros vinculados são apagados com a conta. Contas inativas não são excluídas automaticamente.',
    ta:'பாதுகாப்புப் பதிவுகளில் செயல் வகை, முடிவு, சேவையக நேரம், தொடர்புடைய கணக்கு மட்டும் 30 நாட்கள் சேமிக்கப்படும். காலாவதியானவை மணிநேரத்திற்கு ஒருமுறை நீக்கப்படும். கடவுச்சொல், டோக்கன், மின்னஞ்சல் உள்ளடக்கம், அசல் IP சேமிக்கப்படாது. கணக்கை நீக்கும்போது தொடர்புடைய பதிவுகளும் நீக்கப்படும். செயலற்ற கணக்குகள் தானாக நீக்கப்படாது.',
};
