import type {Language} from './dict';
// Body translations currently available: Japanese and English, clearly labeled in the reader.
const rows:Record<Language,readonly string[]>={
 ja:['利用規約','利用規約とプライバシー説明を確認し、同意します。未成年の場合は保護者と確認してください。','同意して続ける','同意せず戻る','同意状態を確認中…','確認・保存できませんでした。再試行するか、戻って再ログインしてください。','再試行','日本語・Englishで全文を確認できます。','規約が更新されています。最新版で開き直してください。'],
 en:['Terms of Use','I have read and agree to the terms and privacy information. Minors should review these with a parent or guardian.','Agree and continue','Go back without agreeing','Checking consent…','Could not check or save consent. Retry, or go back and sign in again.','Retry','Full text is available in Japanese and English.','The terms have changed. Reopen the latest version.'],
 zh:['使用条款','我已阅读并同意条款和隐私说明。未成年人请与监护人共同阅读。','同意并继续','不同意并返回','正在确认同意状态…','无法确认或保存。请重试，或返回重新登录。','重试','全文提供日语和英语版本。','条款已更新，请重新打开最新版本。'],
 ru:['Условия использования','Я прочитал(а) и принимаю условия и сведения о конфиденциальности. Несовершеннолетним следует ознакомиться с ними вместе с опекуном.','Принять и продолжить','Назад без согласия','Проверка согласия…','Не удалось проверить или сохранить согласие. Повторите либо вернитесь и войдите снова.','Повторить','Полный текст доступен на японском и английском.','Условия изменились. Откройте последнюю версию.'],
 fr:['Conditions d’utilisation','J’ai lu et accepte les conditions et les informations de confidentialité. Les mineurs doivent les consulter avec un responsable légal.','Accepter et continuer','Retour sans accepter','Vérification du consentement…','Impossible de vérifier ou enregistrer. Réessayez ou revenez vous reconnecter.','Réessayer','Texte intégral disponible en japonais et en anglais.','Les conditions ont changé. Rouvrez la dernière version.'],
 de:['Nutzungsbedingungen','Ich habe die Bedingungen und Datenschutzhinweise gelesen und stimme zu. Minderjährige sollten sie mit einer erziehungsberechtigten Person lesen.','Zustimmen und fortfahren','Ohne Zustimmung zurück','Zustimmung wird geprüft…','Prüfen oder Speichern fehlgeschlagen. Erneut versuchen oder zurückgehen und neu anmelden.','Erneut versuchen','Volltext auf Japanisch und Englisch verfügbar.','Die Bedingungen haben sich geändert. Neueste Version öffnen.'],
 es:['Condiciones de uso','He leído y acepto las condiciones y la información de privacidad. Los menores deben revisarlas con su tutor.','Aceptar y continuar','Volver sin aceptar','Comprobando consentimiento…','No se pudo comprobar o guardar. Reintenta o vuelve e inicia sesión de nuevo.','Reintentar','Texto completo disponible en japonés e inglés.','Las condiciones han cambiado. Abre la versión más reciente.'],
 tr:['Kullanım koşulları','Koşulları ve gizlilik bilgilerini okudum ve kabul ediyorum. Reşit olmayanlar bir veliyle incelemelidir.','Kabul et ve devam et','Kabul etmeden geri dön','Onay kontrol ediliyor…','Kontrol edilemedi veya kaydedilemedi. Yeniden deneyin ya da geri dönüp tekrar giriş yapın.','Yeniden dene','Tam metin Japonca ve İngilizce olarak mevcuttur.','Koşullar değişti. En son sürümü yeniden açın.'],
 pl:['Warunki korzystania','Przeczytałem(-am) i akceptuję warunki oraz informacje o prywatności. Osoby niepełnoletnie powinny zapoznać się z nimi z opiekunem.','Akceptuj i kontynuuj','Wróć bez akceptacji','Sprawdzanie zgody…','Nie można sprawdzić lub zapisać. Ponów albo wróć i zaloguj się ponownie.','Ponów','Pełny tekst dostępny po japońsku i angielsku.','Warunki się zmieniły. Otwórz najnowszą wersję.'],
 hi:['उपयोग की शर्तें','मैंने शर्तें और गोपनीयता जानकारी पढ़ी है और सहमत हूँ। नाबालिग इन्हें अभिभावक के साथ पढ़ें।','सहमत होकर जारी रखें','बिना सहमति वापस जाएँ','सहमति जाँची जा रही है…','जाँच या सेव नहीं हुआ। फिर कोशिश करें या वापस जाकर फिर लॉग इन करें।','फिर कोशिश करें','पूरा पाठ जापानी और अंग्रेज़ी में उपलब्ध है।','शर्तें बदल गई हैं। नवीनतम संस्करण फिर खोलें।'],
 pt:['Termos de uso','Li e aceito os termos e as informações de privacidade. Menores devem lê-los com um responsável.','Aceitar e continuar','Voltar sem aceitar','Verificando consentimento…','Não foi possível verificar ou salvar. Tente novamente ou volte e entre de novo.','Tentar novamente','Texto completo disponível em japonês e inglês.','Os termos mudaram. Abra a versão mais recente.'],
 ta:['பயன்பாட்டு விதிமுறைகள்','விதிமுறைகளையும் தனியுரிமைத் தகவலையும் படித்து ஏற்கிறேன். சிறார்கள் பாதுகாவலருடன் படிக்க வேண்டும்.','ஏற்றுத் தொடரவும்','ஏற்காமல் திரும்பவும்','ஒப்புதல் சரிபார்க்கப்படுகிறது…','சரிபார்க்க அல்லது சேமிக்க முடியவில்லை. மீண்டும் முயலவும் அல்லது திரும்பி மீண்டும் உள்நுழையவும்.','மீண்டும் முயலவும்','முழு உரை ஜப்பானிய மற்றும் ஆங்கில மொழிகளில் உள்ளது.','விதிமுறைகள் மாறிவிட்டன. புதிய பதிப்பைத் திறக்கவும்.'],
};
export const termsText=(lang:Language)=>rows[lang];
