import type { Language } from './dict';

type Copy = Readonly<{ free: string; member: string; next: string; day: string; rule: string; cap: string; streak: string; expiry: string; claimed: string }>;
const copy: Record<Language, Copy> = {
    en: { free: 'Free tickets', member: 'Member tickets', next: 'Next login reward (UTC)', day: 'Day', rule: '3 ranked games started per UTC day are free. Each later game costs 1 ranked ticket. Waiting and canceled starts cost no tickets.', cap: 'Free tickets: up to 20 of each kind. Only the space available is credited.', streak: 'Claim on consecutive UTC days to advance through days 1–7. Day 7 repeats; a missed day resets to day 1.', expiry: 'Member tickets are separate from free tickets. Unused member tickets expire at membership end, refund or payment reversal and do not carry over when you rejoin.', claimed: 'Today’s login reward has been claimed.' },
    ja: { free: '無料券', member: '会員券', next: '次のログイン報酬（UTC）', day: '日目', rule: 'UTC日付で開始したランク戦は1日3試合まで無料。4試合目以降は対局券1枚を使用します。待機・開始前キャンセルでは消費しません。', cap: '無料券は各20枚まで。空き枚数の範囲で付与されます。', streak: 'UTC日付で毎日受け取ると1〜7日目へ進み、7日目以降は同じ報酬が続きます。1日逃すと1日目に戻ります。', expiry: '会員券は無料券とは別枠です。会員終了・返金・決済取消で未使用の会員券は失効し、再加入へ持ち越せません。', claimed: '今日のログイン報酬は受取済みです。' },
    zh: { free: '免费券', member: '会员券', next: '下次登录奖励（UTC）', day: '天', rule: '每个UTC日期开始的前3场排位赛免费。之后每场使用1张排位赛券。等待和开局前取消不消耗券。', cap: '免费券每种最多20张，只补充到上限。', streak: '按UTC日期连续领取可升至第7天，第7天奖励持续重复。漏领一天会回到第1天。', expiry: '会员券与免费券分开。会员结束、退款或付款撤销时，未用会员券失效，再加入也不会恢复。', claimed: '今天的登录奖励已领取。' },
    ru: { free: 'Бесплатные билеты', member: 'Билеты подписки', next: 'Следующая награда за вход (UTC)', day: 'День', rule: 'Первые 3 рейтинговые игры, начатые за сутки UTC, бесплатны. Затем каждая игра стоит 1 билет. Ожидание и отмена до старта билеты не расходуют.', cap: 'До 20 бесплатных билетов каждого вида. Начисляется только доступное место.', streak: 'Получайте награду каждый день UTC, чтобы пройти дни 1–7. День 7 повторяется; пропуск возвращает к дню 1.', expiry: 'Билеты подписки учитываются отдельно. Неиспользованные билеты сгорают при окончании подписки, возврате или отмене платежа и не восстанавливаются при повторной подписке.', claimed: 'Сегодняшняя награда за вход уже получена.' },
    fr: { free: 'Tickets gratuits', member: 'Tickets d’abonnement', next: 'Prochaine récompense de connexion (UTC)', day: 'Jour', rule: 'Les 3 premières parties classées commencées par jour UTC sont gratuites. Ensuite, chaque partie coûte 1 ticket. L’attente et l’annulation avant le début ne coûtent rien.', cap: '20 tickets gratuits maximum par type. Seule la place disponible est créditée.', streak: 'Recevez la récompense chaque jour UTC pour progresser du jour 1 au jour 7. Le jour 7 se répète ; un jour manqué ramène au jour 1.', expiry: 'Les tickets d’abonnement sont séparés. Les tickets inutilisés expirent à la fin de l’abonnement, au remboursement ou à l’annulation du paiement et ne sont pas récupérés lors d’un réabonnement.', claimed: 'La récompense de connexion du jour a été reçue.' },
    de: { free: 'Kostenlose Tickets', member: 'Mitgliedschafts-Tickets', next: 'Nächste Anmeldebelohnung (UTC)', day: 'Tag', rule: 'Die ersten 3 pro UTC-Tag gestarteten Ranglistenspiele sind kostenlos. Danach kostet jedes Spiel 1 Ticket. Warten und Abbruch vor dem Start kosten keine Tickets.', cap: 'Bis zu 20 kostenlose Tickets je Art. Nur der verfügbare Platz wird aufgefüllt.', streak: 'Täglich nach UTC abholen, um Tag 1–7 zu erreichen. Tag 7 wiederholt sich; ein ausgelassener Tag setzt auf Tag 1 zurück.', expiry: 'Mitgliedschafts-Tickets werden getrennt geführt. Ungenutzte Tickets verfallen bei Mitgliedschaftsende, Erstattung oder Zahlungsrücknahme und werden bei erneutem Beitritt nicht übertragen.', claimed: 'Die heutige Anmeldebelohnung wurde abgeholt.' },
    es: { free: 'Boletos gratuitos', member: 'Boletos de membresía', next: 'Próxima recompensa de inicio de sesión (UTC)', day: 'Día', rule: 'Las primeras 3 partidas clasificadas iniciadas por día UTC son gratis. Luego cada partida cuesta 1 boleto. Esperar o cancelar antes de empezar no consume boletos.', cap: 'Máximo 20 boletos gratuitos de cada tipo. Solo se acredita el espacio disponible.', streak: 'Reclama cada día UTC para avanzar del día 1 al 7. El día 7 se repite; perder un día reinicia al día 1.', expiry: 'Los boletos de membresía son independientes. Los no usados vencen al terminar la membresía, recibir un reembolso o anular el pago y no se conservan al volver a suscribirse.', claimed: 'Ya recibiste la recompensa de inicio de sesión de hoy.' },
    tr: { free: 'Ücretsiz biletler', member: 'Üyelik biletleri', next: 'Sonraki giriş ödülü (UTC)', day: 'Gün', rule: 'UTC gününde başlatılan ilk 3 dereceli maç ücretsizdir. Sonraki her maç 1 bilet kullanır. Bekleme ve başlamadan iptal bilet tüketmez.', cap: 'Her türden en fazla 20 ücretsiz bilet. Yalnızca boş kapasite kadar eklenir.', streak: '1–7. günlere ilerlemek için her UTC günü ödülü alın. 7. gün tekrarlanır; bir gün kaçırmak 1. güne döndürür.', expiry: 'Üyelik biletleri ayrı tutulur. Kullanılmayan biletler üyelik sonunda, iadede veya ödeme iptalinde sona erer; yeniden katılımda aktarılmaz.', claimed: 'Bugünün giriş ödülü alındı.' },
    pl: { free: 'Darmowe bilety', member: 'Bilety członkowskie', next: 'Następna nagroda za logowanie (UTC)', day: 'Dzień', rule: 'Pierwsze 3 gry rankingowe rozpoczęte w dniu UTC są darmowe. Każda następna kosztuje 1 bilet. Czekanie i anulowanie przed startem nie zużywa biletów.', cap: 'Do 20 darmowych biletów każdego rodzaju. Przyznawana jest tylko dostępna pojemność.', streak: 'Odbieraj nagrodę każdego dnia UTC, aby przejść dni 1–7. Dzień 7 się powtarza; opuszczenie dnia resetuje do dnia 1.', expiry: 'Bilety członkowskie są oddzielne. Niewykorzystane wygasają przy końcu członkostwa, zwrocie lub cofnięciu płatności i nie przechodzą na ponowne członkostwo.', claimed: 'Dzisiejsza nagroda za logowanie została odebrana.' },
    hi: { free: 'मुफ़्त टिकट', member: 'सदस्यता टिकट', next: 'अगला लॉगिन इनाम (UTC)', day: 'दिन', rule: 'हर UTC दिन शुरू किए गए पहले 3 रैंक्ड मैच मुफ़्त हैं। इसके बाद हर मैच में 1 टिकट लगता है। प्रतीक्षा और शुरुआत से पहले रद्द करने पर टिकट नहीं लगता।', cap: 'हर प्रकार के अधिकतम 20 मुफ़्त टिकट। केवल खाली जगह तक टिकट दिए जाते हैं।', streak: 'हर UTC दिन इनाम लेकर दिन 1–7 तक बढ़ें। दिन 7 दोहराता है; एक दिन छूटने पर दिन 1 से शुरुआत होती है।', expiry: 'सदस्यता टिकट मुफ़्त टिकट से अलग हैं। सदस्यता समाप्त होने, धनवापसी या भुगतान रद्द होने पर बचे सदस्यता टिकट समाप्त होते हैं और दोबारा जुड़ने पर वापस नहीं आते।', claimed: 'आज का लॉगिन इनाम मिल चुका है।' },
    pt: { free: 'Bilhetes gratuitos', member: 'Bilhetes da assinatura', next: 'Próxima recompensa de login (UTC)', day: 'Dia', rule: 'As primeiras 3 partidas ranqueadas iniciadas por dia UTC são grátis. Depois, cada partida custa 1 bilhete. Esperar ou cancelar antes do início não consome bilhetes.', cap: 'Até 20 bilhetes gratuitos de cada tipo. Só é creditado o espaço disponível.', streak: 'Receba a recompensa a cada dia UTC para avançar do dia 1 ao 7. O dia 7 se repete; perder um dia reinicia no dia 1.', expiry: 'Bilhetes da assinatura são separados. Os não usados expiram no fim da assinatura, no reembolso ou na reversão do pagamento e não passam para uma nova assinatura.', claimed: 'A recompensa de login de hoje já foi recebida.' },
    ta: { free: 'இலவசச் சீட்டுகள்', member: 'உறுப்பினர் சீட்டுகள்', next: 'அடுத்த உள்நுழைவு வெகுமதி (UTC)', day: 'நாள்', rule: 'ஒவ்வொரு UTC நாளிலும் தொடங்கும் முதல் 3 தரவரிசைப் போட்டிகள் இலவசம். அதன் பிறகு ஒவ்வொரு போட்டிக்கும் 1 சீட்டு தேவை. காத்திருப்பதும் தொடங்குமுன் ரத்து செய்வதும் சீட்டுகளைச் செலவிடாது.', cap: 'ஒவ்வொரு வகையிலும் அதிகபட்சம் 20 இலவசச் சீட்டுகள். மீதமுள்ள இடத்திற்கு மட்டுமே வழங்கப்படும்.', streak: 'ஒவ்வொரு UTC நாளும் பெற்று 1–7 நாட்களுக்கு முன்னேறுங்கள். 7ஆம் நாள் மீண்டும் தொடரும்; ஒரு நாள் தவறினால் 1ஆம் நாளுக்கு மீளும்.', expiry: 'உறுப்பினர் சீட்டுகள் தனியாக உள்ளன. உறுப்பினர் காலம் முடிதல், பணத் திருப்பம் அல்லது கட்டண ரத்தின்போது பயன்படுத்தாத சீட்டுகள் காலாவதியாகும்; மீண்டும் சேரும்போது மாற்றப்படாது.', claimed: 'இன்றைய உள்நுழைவு வெகுமதி பெறப்பட்டது.' },
};
export const ticketWalletText = (lang: Language, sharedAdmission = false): Copy => sharedAdmission ? {
    ...copy[lang],
    rule: lang === 'ja'
        ? 'オンライン対戦とランク戦は合計でUTC日付ごとに3試合まで無料。以降は対局ごとに対局券1枚の使用を選択します。待機・開始前キャンセルでは消費しません。有効なStandard／Plus会員は回数無制限・広告なしです。'
        : 'The first 3 online and ranked games combined per UTC day are free. After that, choose to use 1 match ticket for each game. Waiting and canceled starts cost no tickets. Active Standard and Plus members have unlimited games and no ads.',
} : copy[lang];
