import { TERMS_SECTIONS, TERMS_ENGLISH } from './terms';

/** Owner approved. Root sets the actual publication date here and in the DB policy before release. */
export const CURRENT_TERMS_VERSION = '2026-10-03.1';
export const CURRENT_TERMS_EFFECTIVE_DATE: string | null = null;
export function currentTermsEffective(date: string | null = CURRENT_TERMS_EFFECTIVE_DATE, now = Date.now()): boolean {
    if (!date || !/^\d{4}-\d{2}-\d{2}$/.test(date)) return false;
    const utc = Date.parse(`${date}T00:00:00Z`);
    return Number.isFinite(utc) && new Date(utc).toISOString().slice(0, 10) === date && Date.parse(`${date}T00:00:00+09:00`) <= now;
}
export const CURRENT_TERMS_SECTIONS = TERMS_SECTIONS.map(([title, body], index): readonly [string, string] => {
    if (index === 2) return ['料金・無料券・Web会員',
        '各機能の提供開始後は、以下の条件を適用します。新規購入の受付状況は購入画面に表示します。\n無料ランク戦はアカウントごとにUTC日付で開始した1日3試合までです。4試合目以降は対局券1枚を使用します。待機・マッチ不成立・開始前キャンセルでは消費しません。開始後の障害等で返還対象となった券は、通常の保有上限によって失われない返還分として別に管理します。会員券の返還分には元の会員資格・有効期限が適用されます。\n連続ログイン1〜7日目の対局券は1・1・1・2・2・2・3枚、CPU練習ヒント券は2・2・3・3・4・4・5枚です。7日目以降は最大段階を継続し、UTC日付で1日逃すと1日目に戻ります。無料券は各20枚まで、空き枚数の範囲で付与します。本人確認と本規約への同意後に受け取れます。ヒント券はCPU練習専用で、オンライン戦・ランク戦・クラウン・サーキットでは使用しません。\nWeb会員Q-Gambit Plusの月額総額はUSD 2.99です。購入日から1か月ごとに、解約するまで自動更新し、初回購入時と毎月の更新時に請求します。決済成功とサーバー確認後に特典を提供します。有効期間中に毎日ログインすると、対局券3枚とCPU練習ヒント券3枚を受け取れます。会員券は無料券と別枠で各60枚までです。上限を超える分は付与されず、ログインしなかった日や受け取らなかった日分を後からまとめて受け取ることはできません。\n通常の解約はWebの請求管理から次回更新を停止し、支払済み期間の末日まで特典を利用できます。通常解約の日割り返金はありません。適用法令上の権利は制限しません。会員終了・返金・決済取消で未使用の会員券は失効し、再加入へ持ち越しません。無料券は影響を受けません。券は譲渡・換金できません。\n通信費、カード会社の為替換算・手数料は利用者負担となる場合があります。Androidでは既に購入した特典の利用のみを提供し、購入・外部決済への誘導は表示しません。広告は引き続き停止します。'];
    if (index === 5) return [title, body + '\nWeb会員のあるアカウントは、購読解約を確認してからアカウント削除を完了します。削除後は会員特典と未使用券を利用できません。Stripeは決済に必要な情報を処理し、Q-Gambitのサーバーは購読状態・決済通知・券の付与／消費記録を処理します。カード番号をQ-Gambitで保存しません。\n削除後の遅延通知によってアカウントや特典が再作成されないよう、必要最小限の決済処理識別子を分離して保持します。法令・決済事業者側で必要な保存を即時削除できるとは約束しません。'];
    return [title, body];
});
export const CURRENT_TERMS_ENGLISH = TERMS_ENGLISH.map(([title, body], index): readonly [string, string] => {
    if (index === 2) return ['Costs, free tickets and Web membership',
        'The following conditions apply after each feature becomes available. The purchase screen states whether new purchases are available.\nEach account can start 3 ranked games free per UTC day. Each later game costs 1 ranked ticket. Waiting, failed matching and cancellation before the start cost no tickets. Tickets eligible for return after a failure following the start are held as separate refund credits, so ordinary holding caps do not erase them. Returned member tickets retain their original membership eligibility and expiry.\nLogin days 1–7 grant ranked tickets 1,1,1,2,2,2,3 and CPU practice hint tickets 2,2,3,3,4,4,5. Day 7 repeats; missing a UTC day resets the sequence to day 1. Free tickets are capped at 20 of each kind and only available space is credited. Claims require verified identity and acceptance of these terms. Hint tickets are for CPU practice only, not online, ranked, Crown or Circuit games.\nQ-Gambit Plus Web membership costs a final total of USD 2.99 per month. It renews monthly from the purchase date until canceled, with charges at purchase and each monthly renewal. Benefits start after successful payment and server verification. Logging in daily during the active period lets you receive 3 ranked tickets and 3 CPU practice hint tickets. Member tickets are separate from free tickets, with a cap of 60 of each kind. Grants above the cap are not credited. Days without login or collection cannot be claimed retroactively or accumulated for later collection.\nOrdinary cancellation in Web billing settings stops the next renewal; benefits continue until the paid period ends. Ordinary cancellation does not provide a prorated refund. Rights under applicable law are not restricted. Unused member tickets expire at membership end, refund or payment reversal and do not carry over when rejoining. Free tickets are unaffected. Tickets cannot be transferred or exchanged for cash.\nConnectivity costs, currency conversion and card-provider fees may be your responsibility. Android provides use of benefits already purchased, without purchase or external payment prompts. Advertising remains disabled.'];
    if (index === 5) return [title, body + '\nFor accounts with Web membership, subscription cancellation is confirmed before account deletion is completed. After deletion, membership benefits and unused tickets cannot be used. Stripe processes payment information; Q-Gambit servers process subscription status, payment notifications and ticket grant/use records. Q-Gambit does not store card numbers.\nThe minimum payment-processing identifiers needed to prevent delayed notifications from recreating a deleted account or its benefits are retained separately. We do not promise immediate deletion of records that the law or payment provider requires to be retained.'];
    return [title, body];
});
