/** Approved 2026-09-25. Never change a published version's text in place. */
export const TERMS_VERSION='2026-09-25.1';
export const TERMS_EFFECTIVE_DATE='2026-09-25';
export const TERMS_SECTIONS = [
 ['適用範囲','本規約は、Q-Gambit運営（以下「運営」）が提供する量子チェスゲーム「Q-Gambit」のWeb版およびAndroid版に適用します。個人情報の取り扱いは、別途公開するプライバシーポリシーで説明します。'],
 ['利用とアカウント','利用者は規約とプライバシー説明を確認したうえで利用してください。未成年の利用者は保護者と一緒に内容を確認し、必要な同意を得てください。ゲストで利用できる機能と、ログインが必要な機能があります。パスワードは他人に知らせず、不正利用が疑われる場合はパスワード再設定や全端末ログアウトを行ってください。\nプロフィール名、アイコン、レートなどは他の利用者から見える場合があります。実名、連絡先、第三者の写真など、公開を望まない情報は登録しないでください。'],
 ['料金と報酬','現時点で有償通貨・アプリ内購入はありません。通信費などは利用者の負担です。ゲーム内の外観・BGM等の報酬はゲーム内で利用するもので、現金への交換や運営が認めていない売買はできません。広告と広告に連動する回数制限は現在停止しています。課金や広告を導入する場合は、内容・必要な同意・子供を含む利用者への保護を整えて事前に案内します。'],
 ['公正な利用','不正プログラム、他人のアカウント利用、通信・レート・報酬の不正操作、サービスを妨害する大量アクセス、なりすまし、嫌がらせ、権利侵害や違法な画像の登録を禁止します。プログラムの不具合を発見した場合は、他の利用者に影響を与える実証をせず、問い合わせ先へ連絡してください。\n運営は、不正の状況・影響に応じてオンライン機能の制限等を行うことがあります。制限について確認・異議申立てをしたい場合は問い合わせ先へ連絡できます。制限中も、本人確認を伴うアカウント削除の経路は維持します。'],
 ['進行・棋譜・保存','ログインした利用者のサーキット進行と外観選択は、端末内保存とクラウド保存を使用します。通信できない場合などは同期が完了しないことがあるため、端末を変更する前に保存状態を確認してください。旧版の端末内進行は、利用者が選んだアカウントに移行します。\n棋譜一覧は利用者ごとに直近10試合です。共有の棋譜は相手の直近10試合に含まれる間は残る場合があります。レートや勝敗統計は棋譜の件数とは別に管理します。'],
 ['アカウント削除','設定内の削除機能から、本人確認と確認操作を経てアカウントの削除を要求できます。削除対象のアカウント情報・関連データ・棋譜は消去し、相手には匿名化した勝敗記録を残します。相手のレートは変更しません。削除後に元のアカウントや進行を復元できるとは限りません。長期間利用していないという理由だけでアカウントを自動削除することはありません。\nバックアップ等の残存データの扱いは、実際の保存期間を確認してプライバシーポリシーで説明します。未確認の期間を本規約では約束しません。'],
 ['メンテナンスと変更','安全性・安定性の維持のため、更新やメンテナンスを行うことがあります。可能な限り事前告知し、緊急の場合は事後に案内します。対局やデータに問題が生じた場合は、調査のうえ合理的な対応を行います。必要な更新版が利用可能になる前に、旧版を一律に利用不能にすることは避けます。'],
 ['権利と責任','ゲームや素材に関する権利は運営または権利者に帰属します。プレイ映像やスクリーンショットの共有では、他の利用者の個人情報・第三者の権利に配慮してください。本規約は、適用法令で認められる消費者の権利を制限せず、運営の責任を一律に免除するものではありません。'],
 ['規約の変更','重要な変更は内容と適用日を事前に案内し、必要に応じて再同意を求めます。同意版と同意日時を記録します。同意しない場合でも、問い合わせと本人によるアカウント削除の経路は利用できます。'],
 ['問い合わせ','Q-Gambit運営: qgambit970@gmail.com\n問い合わせには画面に表示されるユーザーIDを使用でき、パスワードや認証コードを送る必要はありません。'],
] as const;
/** English translation; the approved Japanese text remains available alongside it. */
export const TERMS_ENGLISH = [
 ['Scope','These terms apply to the Web and Android versions of Q-Gambit provided by Q-Gambit Operations. Our separate Privacy Policy explains how personal information is handled.'],
 ['Using your account','Please read these terms and the privacy information before using the service. Minors should review them with a parent or guardian and obtain any required consent. Some features allow guest play; others require sign-in. Keep passwords private. If misuse is suspected, reset your password or sign out everywhere.\nYour profile name, icon and rating may be visible to other players. Do not register real names, contact details, photographs of others, or other information you do not wish to make public.'],
 ['Costs and rewards','There is currently no paid currency or in-app purchasing. You are responsible for connectivity costs. Cosmetic and music rewards are for use in the game; they cannot be exchanged for cash or traded without authorization. Ads and ad-linked daily limits are currently disabled. Before introducing payments or ads, we will explain them and arrange necessary consent and safeguards, including safeguards for children.'],
 ['Fair use','Cheating, using another person’s account, manipulating communications, ratings or rewards, disruptive traffic, impersonation, harassment, rights infringements and unlawful images are prohibited. Report vulnerabilities to support without testing them in a way that affects other players.\nWe may restrict online features according to the circumstances and impact of abuse. You can contact support to ask about or appeal restrictions. Verified account-deletion access remains available even during a restriction.'],
 ['Progress and records','Signed-in players’ Circuit progress and appearance selections use both device and cloud storage. Synchronization may not finish when connectivity is unavailable. Check save status before changing devices. Earlier device progress can be assigned to the account you choose.\nEach player’s replay list contains their latest ten matches. Shared replays may remain while they are among the opponent’s latest ten. Ratings and win/loss statistics are maintained separately from the replay limit.'],
 ['Account deletion','You can request deletion in Settings after identity verification and confirmation. The account, associated data and replays are erased; opponents retain anonymized win/loss records and their ratings do not change. Restoration of a deleted account or progress is not guaranteed. Accounts are not automatically deleted merely for being inactive.\nResidual backup handling will be explained in the Privacy Policy after the actual retention period is verified. These terms do not promise an unverified period.'],
 ['Maintenance and changes','Updates and maintenance may be necessary for security and stability. We will give advance notice where possible, or notice afterward in emergencies. We will investigate problems affecting games or data and take reasonable action. We aim not to disable all older versions before the required update becomes available.'],
 ['Rights and responsibility','Game and asset rights belong to the operator or their respective owners. When sharing footage or screenshots, respect others’ personal information and third-party rights. These terms do not restrict consumer rights under applicable law or generally exclude the operator’s responsibility.'],
 ['Changes to these terms','Important changes and their effective date will be announced in advance, with renewed consent requested when needed. The accepted version and acceptance time are recorded. Support and verified account deletion remain available if you do not agree.'],
 ['Contact','Q-Gambit Operations: qgambit970@gmail.com\nYou may use your displayed user ID when contacting support. Never send passwords or verification codes.'],
] as const;
